// constants/healthcareCenters.js

export const HEALTHCARE_CENTERS = [
    {
      id: "HC001",
      name: "City Hospital",
      location: "123 Main St, Citytown",
      contactNumber: "555-123-4567",
      email: "cityhospital@example.com",
      facilities: ["Emergency", "Radiology", "Pharmacy"],
      numberOfBeds: 100,
      numberOfStaff: 50,
      accreditations: ["JCI", "NABH"],
      operatingHours: "24/7",
      profileStatus: "Active",
      lastUpdated: "2024-08-01",
    },
    {
      id: "HC002",
      name: "Green Valley Clinic",
      location: "456 Oak Rd, Greentown",
      contactNumber: "555-234-5678",
      email: "gvclinic@example.com",
      facilities: ["General Practice", "Pediatrics"],
      numberOfBeds: 20,
      numberOfStaff: 10,
      accreditations: ["ISO 9001"],
      operatingHours: "8am-8pm",
      profileStatus: "Active",
      lastUpdated: "2024-08-03",
    },
    {
      id: "HC003",
      name: "Mountain View Medical",
      location: "789 Pine Ave, Mountown",
      contactNumber: "555-345-6789",
      email: "mvmedical@example.com",
      facilities: ["Surgery", "Rehabilitation", "Maternity"],
      numberOfBeds: 150,
      numberOfStaff: 100,
      accreditations: ["JCI"],
      operatingHours: "7am-10pm",
      profileStatus: "Inactive",
      lastUpdated: "2024-07-28",
    },
    {
      id: "HC004",
      name: "Lakeside Health Center",
      location: "101 Lake St, Laketown",
      contactNumber: "555-456-7890",
      email: "lakesidehc@example.com",
      facilities: ["Cardiology", "Orthopedics", "Neurology"],
      numberOfBeds: 200,
      numberOfStaff: 120,
      accreditations: ["NABH"],
      operatingHours: "24/7",
      profileStatus: "Pending",
      lastUpdated: "2024-07-30",
    },
    {
      id: "HC005",
      name: "Riverbend Hospital",
      location: "202 River Rd, Rivertown",
      contactNumber: "555-567-8901",
      email: "riverbend@example.com",
      facilities: ["ICU", "Pathology", "Urology"],
      numberOfBeds: 80,
      numberOfStaff: 60,
      accreditations: ["JCI", "NABH", "ISO"],
      operatingHours: "24/7",
      profileStatus: "Active",
      lastUpdated: "2024-08-05",
    },
  ];
  