export const specialist = [
{title: 'Allergists/Immunologists '},
{title: 'Anesthesiologists'},
{title: 'Cardiologists'},
{title: 'Colon and Rectal Surgeons'},
{title: 'Intensivists'},
{title: 'Dermatologists'},
{title: 'Endocrinologists'},
{title: 'Family Physicians'},
{title: 'Gastroenterologists'},
{title: 'Geriatricians'},
{title: 'Hematologists'},
{title: 'Hospice and Palliative Medicine Specialists'},
{title: 'Infectiology'},
{title: 'Internists'},
{title: 'Medical Geneticists'},
{title: 'Nephrologists'},
{title: 'Neurologists'},
{title: 'Obstetricians'},
{title: 'Gynecologists'},
{title: 'Oncologists'},
{title: 'Ophthalmologists'},
{title: 'Osteopaths'},
{title:'Otolaryngologists'},
{title: 'Pathologists'},
{title: 'Pediatricians'},
{title: 'Physiatrists'},
{title: 'Plastic Surgeons'},
{title: 'Podiatrists'},
{title: 'Preventive Medicine Specialists'},
{title: 'Psychiatrists'},
{title: 'Pulmonologists'},
{title: 'Radiologists'},
{title: 'Rheumatologists'},
{title: 'Sleep Medicine Specialists'},
{title: 'Sports Medicine Specialists'},
{title: 'General Surgeons'},
{title: 'Urologists'},
]