import * as dotenv from "dotenv";
import * as path from "path";
import { createClient } from "@supabase/supabase-js";

// Load environment variables from .env.local
dotenv.config({ path: path.join(process.cwd(), ".env.local") });

// ─────────────────────────────────────────────────────────────
// One-off content top-up, run once during the free-tier gating work
// (PLAN.md "Part 0b"). equipmentAccessMap in
// features/fitness/data/generate-plan.ts was just fixed to use the real
// fitness_exercises.equipment_required values instead of strings that
// barely existed in the table -- that alone fixes the "nearly empty pool"
// problem for no_equipment/basic users. These four equipment types are
// still too thin in absolute terms (2-12 rows) to give real variety within
// a full_gym plan that leans on them, so this inserts 25 hand-authored,
// schema-matching rows per type directly via the service-role client --
// no OpenAI call (no key available in this environment); content is
// authored inline below instead.
//
// Deliberately bypasses lib/db/admin.ts's getAdminClient() (guarded by
// `import "server-only"`, which throws outside a Next.js bundler context —
// a plain `tsx` run has no such resolution) and the admin dialog's
// create-exercise path, whose zod enums (schemas/exercise.schema.ts) are
// themselves stale relative to the live data (confirmed 2026-09-08: none of
// its EQUIPMENT_TYPES values match "TRX/Suspension Trainer", "Cable
// Machine", etc.; primary_muscle_group values like "Shoulders"/"Forearms"
// aren't in its CATEGORIES enum either). That's a separate, pre-existing
// drift issue in the admin UI -- not fixed here.
// ─────────────────────────────────────────────────────────────

function getScriptAdminClient() {
  const url = process.env.NEXT_PUBLIC_SUPABASE_URL;
  const serviceKey =
    process.env.SUPABASE_SECRET_KEY ||
    process.env.SUPABASE_SERVICE_ROLE_KEY ||
    process.env.SERVICE_KEY;
  if (!url) throw new Error("NEXT_PUBLIC_SUPABASE_URL is not set.");
  if (!serviceKey) throw new Error("SUPABASE_SECRET_KEY is not set.");
  return createClient(url, serviceKey, {
    auth: { persistSession: false, autoRefreshToken: false },
  });
}

type Category = "strength" | "cardio" | "stretching";
type Difficulty = "beginner" | "intermediate" | "advanced" | "expert";

interface ExerciseRow {
  exercise_name: string;
  category: Category;
  primary_muscle_group: string;
  secondary_muscles: string;
  difficulty_level: Difficulty;
  default_sets: string;
  default_reps_duration: string;
  rest_time_seconds: string;
  description: string;
  benefits: string;
  met_value: number;
}

const ROWING_MACHINE: ExerciseRow[] = [
  { exercise_name: "Steady-State Row", category: "cardio", primary_muscle_group: "Back", secondary_muscles: "Legs, Core", difficulty_level: "beginner", default_sets: "1", default_reps_duration: "15 min", rest_time_seconds: "0", description: "Row at a consistent, conversational pace, driving with the legs before pulling through with the back and arms.", benefits: "Builds aerobic base and reinforces the leg-hip-arm rowing sequence.", met_value: 7 },
  { exercise_name: "Rowing Intervals 250m", category: "cardio", primary_muscle_group: "Back", secondary_muscles: "Legs, Core", difficulty_level: "intermediate", default_sets: "6", default_reps_duration: "250m", rest_time_seconds: "60", description: "Row 250 meters at a hard pace, then rest before repeating.", benefits: "Develops rowing power and anaerobic capacity.", met_value: 9 },
  { exercise_name: "Rowing Intervals 500m", category: "cardio", primary_muscle_group: "Back", secondary_muscles: "Legs, Core", difficulty_level: "advanced", default_sets: "5", default_reps_duration: "500m", rest_time_seconds: "90", description: "Row 500 meters at a strong, sustainable pace for each interval.", benefits: "Improves rowing-specific conditioning and pacing discipline.", met_value: 9 },
  { exercise_name: "Power Strokes (10 Stroke Sprints)", category: "cardio", primary_muscle_group: "Legs", secondary_muscles: "Back, Core", difficulty_level: "advanced", default_sets: "8", default_reps_duration: "10 strokes", rest_time_seconds: "45", description: "Explode through 10 maximal-effort strokes, emphasizing leg drive, then recover.", benefits: "Builds explosive leg power and rowing peak output.", met_value: 9 },
  { exercise_name: "Single-Arm Rowing Drill", category: "strength", primary_muscle_group: "Back", secondary_muscles: "Core", difficulty_level: "intermediate", default_sets: "3", default_reps_duration: "10 strokes per side", rest_time_seconds: "60", description: "Row using one arm at a time while keeping the torso square, alternating sides.", benefits: "Isolates the pulling muscles and highlights left-right imbalances.", met_value: 6 },
  { exercise_name: "Reverse Rowing (Push Away Focus)", category: "strength", primary_muscle_group: "Legs", secondary_muscles: "Glutes", difficulty_level: "beginner", default_sets: "3", default_reps_duration: "30 sec", rest_time_seconds: "45", description: "Reverse the rowing motion, pushing the handle away and focusing on controlled leg extension.", benefits: "Builds leg drive strength and eccentric control.", met_value: 5 },
  { exercise_name: "Rowing Pyramid Intervals", category: "cardio", primary_muscle_group: "Back", secondary_muscles: "Legs, Core", difficulty_level: "advanced", default_sets: "1", default_reps_duration: "200-400-600-400-200m", rest_time_seconds: "60", description: "Row a pyramid of distances, increasing then decreasing, holding a hard pace throughout.", benefits: "Builds pacing awareness and sustained rowing power.", met_value: 9 },
  { exercise_name: "Low-Drag Technique Row", category: "cardio", primary_muscle_group: "Back", secondary_muscles: "Legs", difficulty_level: "beginner", default_sets: "1", default_reps_duration: "10 min", rest_time_seconds: "0", description: "Row at a light drag setting, focusing purely on smooth sequencing: legs, hips, arms.", benefits: "Grooves clean rowing technique without fatigue interfering.", met_value: 5 },
  { exercise_name: "Rowing Tabata", category: "cardio", primary_muscle_group: "Back", secondary_muscles: "Legs, Core", difficulty_level: "expert", default_sets: "8", default_reps_duration: "20 sec", rest_time_seconds: "10", description: "Alternate 20 seconds of maximal rowing effort with 10 seconds of rest for 4 minutes.", benefits: "Delivers a high-intensity conditioning stimulus in minimal time.", met_value: 10 },
  { exercise_name: "Seated Row Hold (Isometric Finish)", category: "strength", primary_muscle_group: "Back", secondary_muscles: "Core", difficulty_level: "intermediate", default_sets: "3", default_reps_duration: "20 sec hold", rest_time_seconds: "45", description: "Pull the handle to the torso and hold the finished rowing position under tension.", benefits: "Builds isometric back strength and postural endurance.", met_value: 5 },
  { exercise_name: "Rowing Machine Sprint 100m", category: "cardio", primary_muscle_group: "Legs", secondary_muscles: "Back", difficulty_level: "advanced", default_sets: "8", default_reps_duration: "100m", rest_time_seconds: "60", description: "Row 100 meters at an all-out sprint effort, then fully recover before the next rep.", benefits: "Trains maximal rowing power output.", met_value: 9 },
  { exercise_name: "Rowing Ladder (500-400-300-200-100m)", category: "cardio", primary_muscle_group: "Back", secondary_muscles: "Legs, Core", difficulty_level: "advanced", default_sets: "1", default_reps_duration: "500-400-300-200-100m", rest_time_seconds: "60", description: "Row a descending ladder of distances, holding or increasing pace as distance shortens.", benefits: "Builds speed endurance and finishing power.", met_value: 9 },
  { exercise_name: "Rowing Machine Cool-Down Row", category: "cardio", primary_muscle_group: "Back", secondary_muscles: "Legs", difficulty_level: "beginner", default_sets: "1", default_reps_duration: "5 min", rest_time_seconds: "0", description: "Row at a very light, easy pace to bring the heart rate down after a workout.", benefits: "Aids active recovery and gradual heart-rate reduction.", met_value: 3 },
  { exercise_name: "Half-Slide Rowing Drill", category: "strength", primary_muscle_group: "Back", secondary_muscles: "Core", difficulty_level: "beginner", default_sets: "3", default_reps_duration: "45 sec", rest_time_seconds: "45", description: "Row using only the top half of the slide, emphasizing the arm and back pull.", benefits: "Teaches the finish of the stroke in isolation.", met_value: 5 },
  { exercise_name: "Rowing Machine Endurance Row (30 min)", category: "cardio", primary_muscle_group: "Back", secondary_muscles: "Legs, Core", difficulty_level: "intermediate", default_sets: "1", default_reps_duration: "30 min", rest_time_seconds: "0", description: "Sustain a steady, moderate pace for 30 continuous minutes.", benefits: "Builds long-duration aerobic capacity.", met_value: 7 },
  { exercise_name: "Rowing Sprint-Recovery Circuit", category: "cardio", primary_muscle_group: "Back", secondary_muscles: "Legs", difficulty_level: "advanced", default_sets: "6", default_reps_duration: "30 sec sprint / 90 sec easy", rest_time_seconds: "0", description: "Alternate 30 seconds of hard rowing with 90 seconds of easy paddling.", benefits: "Combines conditioning with active recovery training.", met_value: 8 },
  { exercise_name: "Rowing Machine Leg Drive Isolation", category: "strength", primary_muscle_group: "Legs", secondary_muscles: "Glutes", difficulty_level: "beginner", default_sets: "3", default_reps_duration: "45 sec", rest_time_seconds: "45", description: "Row using only the legs, keeping the arms and back locked in place through the stroke.", benefits: "Builds leg drive strength that anchors the full rowing stroke.", met_value: 6 },
  { exercise_name: "Rowing Machine Arms-Only Pull", category: "strength", primary_muscle_group: "Back", secondary_muscles: "Biceps", difficulty_level: "beginner", default_sets: "3", default_reps_duration: "12", rest_time_seconds: "45", description: "Keep the legs straight and pull the handle using only the arms and back.", benefits: "Isolates the pulling muscles used in the finish of the stroke.", met_value: 5 },
  { exercise_name: "Rowing Machine Core-Engaged Row", category: "strength", primary_muscle_group: "Core", secondary_muscles: "Back", difficulty_level: "intermediate", default_sets: "3", default_reps_duration: "1 min", rest_time_seconds: "45", description: "Row while deliberately bracing the core through every stroke to protect the spine under load.", benefits: "Reinforces core stability during a compound pulling movement.", met_value: 6 },
  { exercise_name: "Rowing 2k Time Trial", category: "cardio", primary_muscle_group: "Back", secondary_muscles: "Legs, Core", difficulty_level: "expert", default_sets: "1", default_reps_duration: "2000m", rest_time_seconds: "0", description: "Row 2000 meters as fast as possible, pacing to finish strong.", benefits: "The classic rowing benchmark test of aerobic and anaerobic capacity.", met_value: 10 },
  { exercise_name: "Rowing Machine Descending Ladder", category: "cardio", primary_muscle_group: "Back", secondary_muscles: "Legs", difficulty_level: "intermediate", default_sets: "1", default_reps_duration: "400-300-200-100m", rest_time_seconds: "45", description: "Row a shrinking series of distances, holding pace as the intervals get shorter.", benefits: "Builds pacing control and finishing speed.", met_value: 8 },
  { exercise_name: "Rowing Machine EMOM", category: "cardio", primary_muscle_group: "Back", secondary_muscles: "Legs, Core", difficulty_level: "advanced", default_sets: "10", default_reps_duration: "200m each minute", rest_time_seconds: "0", description: "Row 200 meters at the start of every minute, resting for whatever time remains.", benefits: "Trains repeated power output under a fixed time constraint.", met_value: 9 },
  { exercise_name: "Rowing Machine Recovery Row", category: "cardio", primary_muscle_group: "Back", secondary_muscles: "Legs", difficulty_level: "beginner", default_sets: "1", default_reps_duration: "10 min", rest_time_seconds: "0", description: "Row at a very easy pace on a rest day to promote blood flow without adding fatigue.", benefits: "Supports recovery between harder training sessions.", met_value: 4 },
  { exercise_name: "Rowing Machine Negative-Split Row", category: "cardio", primary_muscle_group: "Back", secondary_muscles: "Legs, Core", difficulty_level: "advanced", default_sets: "1", default_reps_duration: "20 min", rest_time_seconds: "0", description: "Row the second half of the piece faster than the first half.", benefits: "Builds pacing discipline and finishing capacity.", met_value: 8 },
  { exercise_name: "Rowing Machine Warm-Up Row", category: "cardio", primary_muscle_group: "Back", secondary_muscles: "Legs", difficulty_level: "beginner", default_sets: "1", default_reps_duration: "5 min", rest_time_seconds: "0", description: "Row at a light, gradually building pace to prepare the body for harder work.", benefits: "Raises heart rate and primes the rowing muscles before a workout.", met_value: 4 },
];

const AB_WHEEL: ExerciseRow[] = [
  { exercise_name: "Kneeling Ab Wheel Rollout", category: "strength", primary_muscle_group: "Core", secondary_muscles: "Shoulders", difficulty_level: "beginner", default_sets: "3", default_reps_duration: "8", rest_time_seconds: "60", description: "From a kneeling position, roll the wheel forward as far as control allows, then pull back to start.", benefits: "Builds anti-extension core strength and shoulder stability.", met_value: 4 },
  { exercise_name: "Standing Ab Wheel Rollout", category: "strength", primary_muscle_group: "Core", secondary_muscles: "Shoulders, Back", difficulty_level: "expert", default_sets: "3", default_reps_duration: "6", rest_time_seconds: "90", description: "From standing, hinge and roll the wheel out to full extension before rolling back up.", benefits: "An advanced full-body anti-extension and hip-hinge strength challenge.", met_value: 6 },
  { exercise_name: "Half-Range Ab Wheel Rollout", category: "strength", primary_muscle_group: "Core", secondary_muscles: "Shoulders", difficulty_level: "beginner", default_sets: "3", default_reps_duration: "10", rest_time_seconds: "60", description: "Roll out only halfway, staying well within a range you can control on the way back.", benefits: "A regression that builds rollout strength before attempting full range.", met_value: 3 },
  { exercise_name: "Ab Wheel Rollout to Plank Hold", category: "strength", primary_muscle_group: "Core", secondary_muscles: "Shoulders", difficulty_level: "intermediate", default_sets: "3", default_reps_duration: "6 + 10 sec hold", rest_time_seconds: "60", description: "Roll out to near-full extension and hold the plank-like position before returning.", benefits: "Combines dynamic rollout strength with static core endurance.", met_value: 5 },
  { exercise_name: "Single-Arm Ab Wheel Rollout", category: "strength", primary_muscle_group: "Core", secondary_muscles: "Shoulders", difficulty_level: "advanced", default_sets: "3", default_reps_duration: "5 per side", rest_time_seconds: "75", description: "Roll the wheel using one hand at a time, resisting rotation throughout.", benefits: "Adds an anti-rotation demand on top of the standard rollout.", met_value: 5 },
  { exercise_name: "Ab Wheel Pike Rollout", category: "strength", primary_muscle_group: "Core", secondary_muscles: "Shoulders", difficulty_level: "advanced", default_sets: "3", default_reps_duration: "8", rest_time_seconds: "60", description: "From a rolled-out position, pike the hips up and back toward the wheel.", benefits: "Targets the lower abdominals with a hip-flexion-driven variation.", met_value: 5 },
  { exercise_name: "Incline Ab Wheel Rollout (Feet Elevated)", category: "strength", primary_muscle_group: "Core", secondary_muscles: "Shoulders", difficulty_level: "advanced", default_sets: "3", default_reps_duration: "6", rest_time_seconds: "75", description: "Perform the rollout with feet elevated on a bench to increase the load on the core.", benefits: "Increases rollout difficulty by shifting more bodyweight onto the arms and core.", met_value: 6 },
  { exercise_name: "Ab Wheel Lateral Rollout (Left)", category: "strength", primary_muscle_group: "Core", secondary_muscles: "Shoulders", difficulty_level: "intermediate", default_sets: "3", default_reps_duration: "8", rest_time_seconds: "60", description: "Roll the wheel diagonally toward the left instead of straight ahead.", benefits: "Trains the oblique muscles with an off-axis rollout path.", met_value: 4 },
  { exercise_name: "Ab Wheel Lateral Rollout (Right)", category: "strength", primary_muscle_group: "Core", secondary_muscles: "Shoulders", difficulty_level: "intermediate", default_sets: "3", default_reps_duration: "8", rest_time_seconds: "60", description: "Roll the wheel diagonally toward the right instead of straight ahead.", benefits: "Trains the oblique muscles with an off-axis rollout path.", met_value: 4 },
  { exercise_name: "Tempo Ab Wheel Rollout (3-Second Eccentric)", category: "strength", primary_muscle_group: "Core", secondary_muscles: "Shoulders", difficulty_level: "intermediate", default_sets: "3", default_reps_duration: "8", rest_time_seconds: "60", description: "Roll out slowly over a 3-second count, then return at a normal pace.", benefits: "Increases time under tension for greater core strength gains.", met_value: 4 },
  { exercise_name: "Ab Wheel Rollout Isometric Hold", category: "strength", primary_muscle_group: "Core", secondary_muscles: "Shoulders", difficulty_level: "intermediate", default_sets: "3", default_reps_duration: "15 sec hold", rest_time_seconds: "60", description: "Roll out to a challenging but controllable position and hold it.", benefits: "Builds static anti-extension strength at end range.", met_value: 4 },
  { exercise_name: "Wall-Assisted Ab Wheel Rollout", category: "strength", primary_muscle_group: "Core", secondary_muscles: "Shoulders", difficulty_level: "beginner", default_sets: "3", default_reps_duration: "10", rest_time_seconds: "45", description: "Roll toward a wall so it limits how far the wheel can travel, providing a safety stop.", benefits: "A beginner-friendly way to build confidence with the rollout pattern.", met_value: 3 },
  { exercise_name: "Ab Wheel Rollout with Pause at Extension", category: "strength", primary_muscle_group: "Core", secondary_muscles: "Shoulders", difficulty_level: "advanced", default_sets: "3", default_reps_duration: "6", rest_time_seconds: "75", description: "Roll out to full extension and pause for 2 seconds before rolling back.", benefits: "Adds time under tension at the hardest point of the movement.", met_value: 5 },
  { exercise_name: "Kneeling Ab Wheel Circle", category: "strength", primary_muscle_group: "Core", secondary_muscles: "Shoulders", difficulty_level: "advanced", default_sets: "3", default_reps_duration: "5 per direction", rest_time_seconds: "75", description: "Roll the wheel in a controlled circular path around the kneeling position.", benefits: "Challenges the core through a multi-directional stability demand.", met_value: 5 },
  { exercise_name: "Ab Wheel Rollout Ladder (Increasing Range)", category: "strength", primary_muscle_group: "Core", secondary_muscles: "Shoulders", difficulty_level: "intermediate", default_sets: "1", default_reps_duration: "5 sets, increasing range each set", rest_time_seconds: "45", description: "Start with short rollouts and progressively increase the range each set.", benefits: "Builds toward full-range rollouts within a single session.", met_value: 4 },
  { exercise_name: "Ab Wheel Rollout Superset Finisher", category: "strength", primary_muscle_group: "Core", secondary_muscles: "Shoulders", difficulty_level: "advanced", default_sets: "3", default_reps_duration: "10", rest_time_seconds: "30", description: "Perform rollouts back-to-back with another core movement to close out a workout.", benefits: "Maximizes core fatigue as a session finisher.", met_value: 5 },
  { exercise_name: "Ab Wheel Knee-to-Rollout Combo", category: "strength", primary_muscle_group: "Core", secondary_muscles: "Hips", difficulty_level: "intermediate", default_sets: "3", default_reps_duration: "8", rest_time_seconds: "60", description: "Alternate a rollout rep with a kneeling hip-flexion drive back to the start position.", benefits: "Combines anti-extension and hip-flexor engagement in one flow.", met_value: 5 },
  { exercise_name: "Banded Ab Wheel Rollout (Assisted)", category: "strength", primary_muscle_group: "Core", secondary_muscles: "Shoulders", difficulty_level: "beginner", default_sets: "3", default_reps_duration: "10", rest_time_seconds: "45", description: "Loop a resistance band around the wheel and anchor point to assist the return.", benefits: "Makes the full-range rollout accessible earlier in training.", met_value: 3 },
  { exercise_name: "Ab Wheel Rollout Negative Only", category: "strength", primary_muscle_group: "Core", secondary_muscles: "Shoulders", difficulty_level: "advanced", default_sets: "3", default_reps_duration: "6", rest_time_seconds: "75", description: "Roll out under slow control and reset from the floor rather than pulling back.", benefits: "Emphasizes the eccentric portion, which is often the limiting strength factor.", met_value: 5 },
  { exercise_name: "Ab Wheel Rollout Pulse", category: "strength", primary_muscle_group: "Core", secondary_muscles: "Shoulders", difficulty_level: "intermediate", default_sets: "3", default_reps_duration: "10 pulses", rest_time_seconds: "60", description: "Roll out partway and pulse in a small range at the hardest point.", benefits: "Adds extra time under tension at end range without full extension.", met_value: 4 },
  { exercise_name: "Ab Wheel Rollout on Decline Bench", category: "strength", primary_muscle_group: "Core", secondary_muscles: "Shoulders", difficulty_level: "expert", default_sets: "3", default_reps_duration: "5", rest_time_seconds: "90", description: "Perform the kneeling rollout on a decline bench to increase the resistance.", benefits: "A high-difficulty variation for advanced core strength.", met_value: 6 },
  { exercise_name: "Ab Wheel Rollout Hold and Row Back", category: "strength", primary_muscle_group: "Core", secondary_muscles: "Back", difficulty_level: "advanced", default_sets: "3", default_reps_duration: "6", rest_time_seconds: "75", description: "Roll out, hold briefly, then actively pull (row) the wheel back rather than letting momentum help.", benefits: "Adds a strength-focused pulling component to the return phase.", met_value: 5 },
  { exercise_name: "Two-Point Ab Wheel Rollout (Alternating Leg Lift)", category: "strength", primary_muscle_group: "Core", secondary_muscles: "Glutes", difficulty_level: "expert", default_sets: "3", default_reps_duration: "4 per side", rest_time_seconds: "90", description: "Roll out while lifting one knee off the ground, alternating sides between reps.", benefits: "Removes a point of support to demand extra anti-rotation control.", met_value: 6 },
  { exercise_name: "Ab Wheel Rollout Warm-Up Drill", category: "strength", primary_muscle_group: "Core", secondary_muscles: "Shoulders", difficulty_level: "beginner", default_sets: "2", default_reps_duration: "8", rest_time_seconds: "30", description: "Perform easy, short-range rollouts to prime the core before heavier core work.", benefits: "Warms up the shoulders and core for the rollout pattern.", met_value: 3 },
  { exercise_name: "Ab Wheel Rollout 3-Point Stability Drill", category: "strength", primary_muscle_group: "Core", secondary_muscles: "Shoulders", difficulty_level: "advanced", default_sets: "3", default_reps_duration: "6 per side", rest_time_seconds: "75", description: "Roll out with one knee lifted slightly off the floor, resisting the urge to rotate.", benefits: "Builds asymmetric core stability under a loaded rollout.", met_value: 5 },
];

const SLED_PROWLER: ExerciseRow[] = [
  { exercise_name: "Sled Push (Low Handles)", category: "cardio", primary_muscle_group: "Legs", secondary_muscles: "Glutes, Core", difficulty_level: "intermediate", default_sets: "6", default_reps_duration: "20m", rest_time_seconds: "60", description: "Drive the sled forward gripping the low handles, staying low with long strides.", benefits: "Builds leg drive power with a low back-friendly forward lean.", met_value: 8 },
  { exercise_name: "Sled Push (High Handles)", category: "cardio", primary_muscle_group: "Legs", secondary_muscles: "Glutes", difficulty_level: "beginner", default_sets: "6", default_reps_duration: "20m", rest_time_seconds: "60", description: "Drive the sled forward using the high handles, keeping a more upright posture.", benefits: "A beginner-friendly sled push with an easier body position.", met_value: 7 },
  { exercise_name: "Sled Backward Drag", category: "strength", primary_muscle_group: "Legs", secondary_muscles: "Core", difficulty_level: "intermediate", default_sets: "4", default_reps_duration: "15m", rest_time_seconds: "60", description: "Hold the straps and walk backward, dragging the sled toward you with controlled steps.", benefits: "Builds quad and knee-stabilizer strength through a low-impact pattern.", met_value: 6 },
  { exercise_name: "Sled Forward Drag (Harness)", category: "strength", primary_muscle_group: "Legs", secondary_muscles: "Glutes", difficulty_level: "intermediate", default_sets: "4", default_reps_duration: "20m", rest_time_seconds: "60", description: "Wear a harness attached to the sled and walk forward with driving strides.", benefits: "Builds hip and glute drive without loading the spine.", met_value: 6 },
  { exercise_name: "Sled Lateral Drag", category: "strength", primary_muscle_group: "Legs", secondary_muscles: "Hips", difficulty_level: "advanced", default_sets: "4", default_reps_duration: "15m per side", rest_time_seconds: "60", description: "Attach the sled to a harness and shuffle sideways, resisting the sled's pull.", benefits: "Trains lateral hip strength and frontal-plane stability.", met_value: 7 },
  { exercise_name: "Sled Row Pull", category: "strength", primary_muscle_group: "Back", secondary_muscles: "Biceps", difficulty_level: "intermediate", default_sets: "4", default_reps_duration: "15m", rest_time_seconds: "60", description: "Facing the sled, pull it toward you hand-over-hand on the attached rope.", benefits: "Builds pulling strength and grip endurance.", met_value: 6 },
  { exercise_name: "Sled Sprint Push", category: "cardio", primary_muscle_group: "Legs", secondary_muscles: "Glutes", difficulty_level: "advanced", default_sets: "8", default_reps_duration: "15m", rest_time_seconds: "45", description: "Push the sled as fast as possible for a short distance, then rest and repeat.", benefits: "Develops explosive acceleration power.", met_value: 9 },
  { exercise_name: "Sled Bear Crawl Push", category: "cardio", primary_muscle_group: "Core", secondary_muscles: "Shoulders, Legs", difficulty_level: "advanced", default_sets: "4", default_reps_duration: "10m", rest_time_seconds: "60", description: "Push the sled in a low bear-crawl stance, hands and feet driving together.", benefits: "Combines full-body conditioning with core and shoulder stability demands.", met_value: 8 },
  { exercise_name: "Single-Arm Sled Drag", category: "strength", primary_muscle_group: "Back", secondary_muscles: "Core", difficulty_level: "advanced", default_sets: "3", default_reps_duration: "15m per side", rest_time_seconds: "60", description: "Drag the sled using one hand at a time while walking, resisting torso rotation.", benefits: "Adds an anti-rotation core demand to a loaded drag.", met_value: 7 },
  { exercise_name: "Sled Overhead Carry Push", category: "strength", primary_muscle_group: "Shoulders", secondary_muscles: "Core, Legs", difficulty_level: "expert", default_sets: "4", default_reps_duration: "15m", rest_time_seconds: "75", description: "Hold a light weight overhead while pushing the sled forward.", benefits: "Combines shoulder stability and leg drive under fatigue.", met_value: 8 },
  { exercise_name: "Sled Farmer Drag", category: "strength", primary_muscle_group: "Legs", secondary_muscles: "Forearms", difficulty_level: "intermediate", default_sets: "4", default_reps_duration: "20m", rest_time_seconds: "60", description: "Hold weights in each hand farmer-carry style while dragging the sled forward.", benefits: "Builds grip endurance alongside leg drive.", met_value: 7 },
  { exercise_name: "Sled Prowler Circuit (Push-Pull)", category: "cardio", primary_muscle_group: "Legs", secondary_muscles: "Back, Core", difficulty_level: "advanced", default_sets: "4", default_reps_duration: "20m push + 20m pull", rest_time_seconds: "60", description: "Push the sled one direction, then turn and drag it back using the attached rope.", benefits: "Combines pushing and pulling patterns in one conditioning circuit.", met_value: 8 },
  { exercise_name: "Sled Zercher Push", category: "strength", primary_muscle_group: "Legs", secondary_muscles: "Core", difficulty_level: "expert", default_sets: "4", default_reps_duration: "15m", rest_time_seconds: "75", description: "Cradle a weight in the crook of the elbows while pushing the sled.", benefits: "Adds a demanding core-bracing load to the sled push.", met_value: 8 },
  { exercise_name: "Sled Rope Pull (Seated)", category: "strength", primary_muscle_group: "Back", secondary_muscles: "Biceps", difficulty_level: "intermediate", default_sets: "4", default_reps_duration: "15m", rest_time_seconds: "60", description: "Sit facing the sled and pull it toward you hand-over-hand using the rope.", benefits: "Isolates the pulling muscles without leg involvement.", met_value: 5 },
  { exercise_name: "Sled Rope Pull (Standing)", category: "strength", primary_muscle_group: "Back", secondary_muscles: "Legs", difficulty_level: "intermediate", default_sets: "4", default_reps_duration: "15m", rest_time_seconds: "60", description: "Stand facing the sled and pull it toward you hand-over-hand, stepping back as needed.", benefits: "Builds full-body pulling strength and grip endurance.", met_value: 6 },
  { exercise_name: "Sled Push Isometric Hold", category: "strength", primary_muscle_group: "Legs", secondary_muscles: "Core", difficulty_level: "intermediate", default_sets: "3", default_reps_duration: "15 sec hold", rest_time_seconds: "45", description: "Push against a loaded sled without moving it, holding a driving stance.", benefits: "Builds isometric leg drive strength.", met_value: 6 },
  { exercise_name: "Sled Drag Walking Lunge", category: "strength", primary_muscle_group: "Legs", secondary_muscles: "Glutes", difficulty_level: "advanced", default_sets: "3", default_reps_duration: "10m", rest_time_seconds: "60", description: "Drag the sled behind you while performing walking lunges.", benefits: "Combines unilateral leg strength with loaded conditioning.", met_value: 8 },
  { exercise_name: "Sled Push Sprint Intervals", category: "cardio", primary_muscle_group: "Legs", secondary_muscles: "Glutes", difficulty_level: "advanced", default_sets: "10", default_reps_duration: "10m", rest_time_seconds: "40", description: "Sprint-push the sled for short bursts with brief recovery between each.", benefits: "Trains repeated sprint power and conditioning.", met_value: 9 },
  { exercise_name: "Sled Backward Walk (Quad Focus)", category: "strength", primary_muscle_group: "Legs", secondary_muscles: "Core", difficulty_level: "beginner", default_sets: "3", default_reps_duration: "20m", rest_time_seconds: "45", description: "Walk backward holding the sled straps at a light load, keeping the knees tracking forward.", benefits: "A joint-friendly way to build quad strength and knee control.", met_value: 5 },
  { exercise_name: "Sled Push Recovery Walk", category: "cardio", primary_muscle_group: "Legs", secondary_muscles: "Glutes", difficulty_level: "beginner", default_sets: "2", default_reps_duration: "20m", rest_time_seconds: "30", description: "Push a very lightly loaded sled at a walking pace to promote recovery.", benefits: "Provides light active recovery between harder sled efforts.", met_value: 4 },
  { exercise_name: "Sled Chest Press Push", category: "strength", primary_muscle_group: "Chest", secondary_muscles: "Shoulders, Legs", difficulty_level: "advanced", default_sets: "4", default_reps_duration: "15m", rest_time_seconds: "60", description: "Push the sled with arms extended at chest height, driving through the legs.", benefits: "Adds a pressing demand to the leg-driven sled push.", met_value: 7 },
  { exercise_name: "Sled Drag Ladder (Distance Pyramid)", category: "cardio", primary_muscle_group: "Legs", secondary_muscles: "Back", difficulty_level: "advanced", default_sets: "1", default_reps_duration: "10-20-30-20-10m", rest_time_seconds: "60", description: "Drag the sled through a pyramid of increasing then decreasing distances.", benefits: "Builds work capacity and pacing across varied efforts.", met_value: 8 },
  { exercise_name: "Sled Push Tabata", category: "cardio", primary_muscle_group: "Legs", secondary_muscles: "Glutes, Core", difficulty_level: "expert", default_sets: "8", default_reps_duration: "20 sec", rest_time_seconds: "10", description: "Alternate 20 seconds of hard sled pushing with 10 seconds of rest for 4 minutes.", benefits: "A high-intensity finisher for leg and cardiovascular conditioning.", met_value: 10 },
  { exercise_name: "Sled Warm-Up Push", category: "cardio", primary_muscle_group: "Legs", secondary_muscles: "Glutes", difficulty_level: "beginner", default_sets: "3", default_reps_duration: "15m", rest_time_seconds: "45", description: "Push a lightly loaded sled at an easy pace to prepare for heavier work.", benefits: "Warms up the legs and hips for sled training.", met_value: 5 },
  { exercise_name: "Sled Push and Drag Combo Finisher", category: "cardio", primary_muscle_group: "Legs", secondary_muscles: "Back, Core", difficulty_level: "expert", default_sets: "3", default_reps_duration: "20m push + 20m drag", rest_time_seconds: "60", description: "Push the sled down and immediately drag it back using the rope, without resting between.", benefits: "A demanding full-body finisher combining pushing and pulling.", met_value: 9 },
];

const BATTLE_ROPES: ExerciseRow[] = [
  { exercise_name: "Alternating Battle Rope Waves", category: "cardio", primary_muscle_group: "Shoulders", secondary_muscles: "Core, Back", difficulty_level: "beginner", default_sets: "4", default_reps_duration: "30 sec", rest_time_seconds: "30", description: "Alternate driving each rope up and down in a steady wave pattern.", benefits: "Builds shoulder endurance and cardiovascular conditioning.", met_value: 8 },
  { exercise_name: "Double Battle Rope Waves", category: "cardio", primary_muscle_group: "Shoulders", secondary_muscles: "Core", difficulty_level: "intermediate", default_sets: "4", default_reps_duration: "30 sec", rest_time_seconds: "30", description: "Raise and slam both ropes together at the same time in a synchronized wave.", benefits: "Increases power output through both arms simultaneously.", met_value: 8 },
  { exercise_name: "Battle Rope Slams", category: "cardio", primary_muscle_group: "Shoulders", secondary_muscles: "Core, Back", difficulty_level: "intermediate", default_sets: "5", default_reps_duration: "15", rest_time_seconds: "45", description: "Raise both ropes overhead and slam them down into the floor with full-body force.", benefits: "Develops explosive upper-body power and conditioning.", met_value: 9 },
  { exercise_name: "Battle Rope Circles (In-and-Out)", category: "cardio", primary_muscle_group: "Shoulders", secondary_muscles: "Core", difficulty_level: "intermediate", default_sets: "4", default_reps_duration: "30 sec", rest_time_seconds: "30", description: "Move both ropes in outward circles, keeping continuous tension.", benefits: "Trains shoulder mobility and endurance through a circular pattern.", met_value: 7 },
  { exercise_name: "Battle Rope Lateral Waves", category: "cardio", primary_muscle_group: "Shoulders", secondary_muscles: "Core", difficulty_level: "intermediate", default_sets: "4", default_reps_duration: "30 sec", rest_time_seconds: "30", description: "Sweep both ropes side to side together instead of up and down.", benefits: "Adds a rotational, oblique-engaging demand to the wave pattern.", met_value: 7 },
  { exercise_name: "Battle Rope Jumping Jacks", category: "cardio", primary_muscle_group: "Shoulders", secondary_muscles: "Legs, Core", difficulty_level: "advanced", default_sets: "4", default_reps_duration: "30 sec", rest_time_seconds: "30", description: "Perform waves with the arms while jumping the feet in and out like a jumping jack.", benefits: "Combines upper- and lower-body conditioning in one movement.", met_value: 9 },
  { exercise_name: "Battle Rope Russian Twist Waves", category: "strength", primary_muscle_group: "Core", secondary_muscles: "Shoulders", difficulty_level: "intermediate", default_sets: "3", default_reps_duration: "20", rest_time_seconds: "45", description: "Wave the ropes while rotating the torso side to side in a seated or standing twist.", benefits: "Adds a rotational core demand to the standard wave.", met_value: 6 },
  { exercise_name: "Battle Rope Squat Waves", category: "strength", primary_muscle_group: "Legs", secondary_muscles: "Shoulders", difficulty_level: "intermediate", default_sets: "4", default_reps_duration: "30 sec", rest_time_seconds: "45", description: "Hold a squat position while continuously waving the ropes.", benefits: "Combines lower-body endurance with upper-body conditioning.", met_value: 8 },
  { exercise_name: "Battle Rope Snake Waves", category: "cardio", primary_muscle_group: "Shoulders", secondary_muscles: "Core", difficulty_level: "advanced", default_sets: "4", default_reps_duration: "30 sec", rest_time_seconds: "30", description: "Whip both ropes side to side along the floor in a snake-like pattern.", benefits: "Trains shoulder endurance through a different plane of motion.", met_value: 7 },
  { exercise_name: "Battle Rope Power Slams", category: "cardio", primary_muscle_group: "Shoulders", secondary_muscles: "Back, Core", difficulty_level: "advanced", default_sets: "5", default_reps_duration: "10", rest_time_seconds: "60", description: "Slam the ropes down as explosively as possible on every rep, resetting fully between slams.", benefits: "Maximizes power output on each individual repetition.", met_value: 9 },
  { exercise_name: "Battle Rope Alternating Slams", category: "cardio", primary_muscle_group: "Shoulders", secondary_muscles: "Core", difficulty_level: "intermediate", default_sets: "4", default_reps_duration: "30 sec", rest_time_seconds: "30", description: "Slam one rope down while the other rises, alternating continuously.", benefits: "Builds shoulder power with a continuous, higher-tempo demand.", met_value: 8 },
  { exercise_name: "Battle Rope Plank Waves", category: "strength", primary_muscle_group: "Core", secondary_muscles: "Shoulders", difficulty_level: "advanced", default_sets: "3", default_reps_duration: "20 sec", rest_time_seconds: "45", description: "Hold a plank position on the forearms while a partner or anchor allows rope waves from the ground.", benefits: "Challenges core anti-rotation stability under rhythmic upper-body movement.", met_value: 6 },
  { exercise_name: "Battle Rope Lunge Waves", category: "strength", primary_muscle_group: "Legs", secondary_muscles: "Shoulders", difficulty_level: "advanced", default_sets: "3", default_reps_duration: "10 per side", rest_time_seconds: "45", description: "Step into a lunge while waving the ropes, alternating legs between reps.", benefits: "Combines lower-body strength work with upper-body conditioning.", met_value: 8 },
  { exercise_name: "Battle Rope Spiral Waves", category: "cardio", primary_muscle_group: "Shoulders", secondary_muscles: "Core", difficulty_level: "advanced", default_sets: "4", default_reps_duration: "30 sec", rest_time_seconds: "30", description: "Move the ropes in a spiraling, ever-widening circular pattern.", benefits: "Trains shoulder endurance and coordination through a complex path.", met_value: 7 },
  { exercise_name: "Battle Rope Tabata Waves", category: "cardio", primary_muscle_group: "Shoulders", secondary_muscles: "Core", difficulty_level: "expert", default_sets: "8", default_reps_duration: "20 sec", rest_time_seconds: "10", description: "Alternate 20 seconds of maximal-effort waves with 10 seconds of rest for 4 minutes.", benefits: "A high-intensity conditioning finisher.", met_value: 10 },
  { exercise_name: "Battle Rope Double Slam Jump", category: "cardio", primary_muscle_group: "Shoulders", secondary_muscles: "Legs, Core", difficulty_level: "expert", default_sets: "4", default_reps_duration: "10", rest_time_seconds: "60", description: "Slam both ropes down while jumping both feet back, then jump forward to reset.", benefits: "A demanding full-body power and conditioning combination.", met_value: 10 },
  { exercise_name: "Battle Rope Seated Waves", category: "strength", primary_muscle_group: "Shoulders", secondary_muscles: "Core", difficulty_level: "beginner", default_sets: "3", default_reps_duration: "30 sec", rest_time_seconds: "30", description: "Perform waves while seated on the floor, removing the legs from the movement.", benefits: "Isolates the shoulders and core, useful for lower-body limitations.", met_value: 6 },
  { exercise_name: "Battle Rope Star Jacks", category: "cardio", primary_muscle_group: "Shoulders", secondary_muscles: "Legs", difficulty_level: "advanced", default_sets: "4", default_reps_duration: "30 sec", rest_time_seconds: "30", description: "Combine rope waves with a wide jumping-jack stance for a bigger range of motion.", benefits: "Increases the cardiovascular demand of the standard wave.", met_value: 9 },
  { exercise_name: "Battle Rope Side-to-Side Slams", category: "cardio", primary_muscle_group: "Shoulders", secondary_muscles: "Core", difficulty_level: "intermediate", default_sets: "4", default_reps_duration: "30 sec", rest_time_seconds: "30", description: "Slam both ropes together, alternating the slam point from one side of the body to the other.", benefits: "Adds a rotational component to the standard double slam.", met_value: 8 },
  { exercise_name: "Battle Rope Circuit Finisher", category: "cardio", primary_muscle_group: "Shoulders", secondary_muscles: "Core, Legs", difficulty_level: "advanced", default_sets: "1", default_reps_duration: "5 min circuit", rest_time_seconds: "0", description: "Cycle through waves, slams, and circles in short blocks to close out a workout.", benefits: "Delivers a high-output conditioning finisher combining several patterns.", met_value: 9 },
  { exercise_name: "Battle Rope Warm-Up Waves", category: "cardio", primary_muscle_group: "Shoulders", secondary_muscles: "Core", difficulty_level: "beginner", default_sets: "2", default_reps_duration: "20 sec", rest_time_seconds: "20", description: "Perform easy, light waves to raise the heart rate and prep the shoulders.", benefits: "Warms up the shoulders and cardiovascular system before harder training.", met_value: 5 },
  { exercise_name: "Battle Rope Single-Arm Waves", category: "strength", primary_muscle_group: "Shoulders", secondary_muscles: "Core", difficulty_level: "intermediate", default_sets: "3", default_reps_duration: "20 sec per side", rest_time_seconds: "30", description: "Wave one rope at a time while keeping the other arm still.", benefits: "Isolates each shoulder and highlights left-right imbalances.", met_value: 6 },
  { exercise_name: "Battle Rope Uppercut Waves", category: "cardio", primary_muscle_group: "Shoulders", secondary_muscles: "Core", difficulty_level: "intermediate", default_sets: "4", default_reps_duration: "30 sec", rest_time_seconds: "30", description: "Drive each rope up and across the body in an uppercut-style motion.", benefits: "Adds a rotational, boxing-inspired variation to the standard wave.", met_value: 8 },
  { exercise_name: "Battle Rope EMOM Slams", category: "cardio", primary_muscle_group: "Shoulders", secondary_muscles: "Core, Back", difficulty_level: "advanced", default_sets: "10", default_reps_duration: "15 slams each minute", rest_time_seconds: "0", description: "Perform 15 slams at the start of every minute, resting for whatever time remains.", benefits: "Trains repeated power output under a fixed time constraint.", met_value: 9 },
  { exercise_name: "Battle Rope Cool-Down Waves", category: "cardio", primary_muscle_group: "Shoulders", secondary_muscles: "Core", difficulty_level: "beginner", default_sets: "1", default_reps_duration: "1 min", rest_time_seconds: "0", description: "Perform slow, light waves to bring the heart rate down after a workout.", benefits: "Aids active recovery after high-intensity training.", met_value: 4 },
];

const TARGETS: Array<{ equipment_required: string; rows: ExerciseRow[] }> = [
  { equipment_required: "Rowing Machine", rows: ROWING_MACHINE },
  { equipment_required: "Ab Wheel", rows: AB_WHEEL },
  { equipment_required: "Sled/Prowler", rows: SLED_PROWLER },
  { equipment_required: "Battle Ropes", rows: BATTLE_ROPES },
];

// ~9% tagged 'free', matching the Part 3 bootstrap ratio for the rest of
// the library, so these new rows split free/pro the same way.
const FREE_EVERY_NTH = 11;

async function main() {
  const admin = getScriptAdminClient();
  let totalInserted = 0;

  for (const target of TARGETS) {
    const rows = target.rows.map((ex, i) => ({
      exercise_name: ex.exercise_name,
      category: ex.category,
      primary_muscle_group: ex.primary_muscle_group,
      secondary_muscles: ex.secondary_muscles,
      equipment_required: target.equipment_required,
      difficulty_level: ex.difficulty_level,
      default_sets: ex.default_sets,
      default_reps_duration: ex.default_reps_duration,
      rest_time_seconds: ex.rest_time_seconds,
      description: ex.description,
      benefits: ex.benefits,
      met_value: ex.met_value,
      tier: i % FREE_EVERY_NTH === 0 ? "free" : "pro",
      is_active: true,
      status: "published",
    }));

    const { error, count } = await admin
      .from("fitness_exercises")
      .insert(rows, { count: "exact" });

    if (error) {
      console.error(`Insert failed for ${target.equipment_required}:`, error.message);
      continue;
    }

    console.log(`Inserted ${count ?? rows.length} rows for ${target.equipment_required}.`);
    totalInserted += count ?? rows.length;
  }

  console.log(`Done. Total new exercises inserted: ${totalInserted}`);
}

main().catch(err => {
  console.error(err);
  process.exit(1);
});
