-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.account (
  id text NOT NULL,
  account_id text NOT NULL,
  provider_id text NOT NULL,
  user_id text NOT NULL,
  access_token text,
  refresh_token text,
  id_token text,
  access_token_expires_at timestamp without time zone,
  refresh_token_expires_at timestamp without time zone,
  scope text,
  password text,
  created_at timestamp without time zone NOT NULL DEFAULT now(),
  updated_at timestamp without time zone NOT NULL,
  CONSTRAINT account_pkey PRIMARY KEY (id),
  CONSTRAINT account_user_id_user_id_fk FOREIGN KEY (user_id) REFERENCES public.user(id)
);
CREATE TABLE public.body_parts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL UNIQUE,
  parent_id uuid,
  mesh_id text,
  path USER-DEFINED NOT NULL,
  level integer DEFAULT 0,
  CONSTRAINT body_parts_pkey PRIMARY KEY (id),
  CONSTRAINT body_parts_parent_id_body_parts_id_fk FOREIGN KEY (parent_id) REFERENCES public.body_parts(id)
);
CREATE TABLE public.categories (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  slug text NOT NULL,
  description text,
  parent_id uuid,
  path USER-DEFINED NOT NULL,
  level integer DEFAULT 0,
  type USER-DEFINED NOT NULL DEFAULT 'condition'::category_type,
  CONSTRAINT categories_pkey PRIMARY KEY (id),
  CONSTRAINT categories_parent_id_categories_id_fk FOREIGN KEY (parent_id) REFERENCES public.categories(id)
);
CREATE TABLE public.condition_causes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  condition_id uuid,
  cause_name text NOT NULL,
  other_possible_causes jsonb,
  CONSTRAINT condition_causes_pkey PRIMARY KEY (id),
  CONSTRAINT condition_causes_condition_id_conditions_id_fk FOREIGN KEY (condition_id) REFERENCES public.conditions(id)
);
CREATE TABLE public.condition_body_parts (
  condition_id uuid NOT NULL,
  body_part_id uuid NOT NULL,
  CONSTRAINT condition_body_parts_pkey PRIMARY KEY (body_part_id, condition_id),
  CONSTRAINT condition_body_parts_condition_id_conditions_id_fk FOREIGN KEY (condition_id) REFERENCES public.conditions(id),
  CONSTRAINT condition_body_parts_body_part_id_body_parts_id_fk FOREIGN KEY (body_part_id) REFERENCES public.body_parts(id)
);
CREATE TABLE public.condition_categories (
  condition_id uuid NOT NULL,
  category_id uuid NOT NULL,
  CONSTRAINT condition_categories_pkey PRIMARY KEY (category_id, condition_id),
  CONSTRAINT condition_categories_condition_id_conditions_id_fk FOREIGN KEY (condition_id) REFERENCES public.conditions(id),
  CONSTRAINT condition_categories_category_id_categories_id_fk FOREIGN KEY (category_id) REFERENCES public.categories(id)
);
CREATE TABLE public.condition_types (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  condition_id uuid,
  type_name text NOT NULL,
  about_type jsonb,
  CONSTRAINT condition_types_pkey PRIMARY KEY (id),
  CONSTRAINT condition_types_condition_id_conditions_id_fk FOREIGN KEY (condition_id) REFERENCES public.conditions(id)
);
CREATE TABLE public.conditions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text,
  slug text,
  nhs_link text,
  image_url text,
  about jsonb,
  diagnosis jsonb,
  treatment jsonb,
  complications jsonb,
  symptoms jsonb,
  prevention jsonb,
  contact_your_doctor jsonb,
  more_information jsonb,
  attribution jsonb,
  is_systemic boolean DEFAULT false,
  search_vector tsvector,
  specialist text,
  created_at timestamp without time zone NOT NULL DEFAULT now(),
  updated_at timestamp without time zone NOT NULL DEFAULT now(),
  status text DEFAULT 'published'::text CHECK (status = ANY (ARRAY['draft'::text, 'published'::text, 'archived'::text, 'pending_review'::text])),
  is_featured boolean DEFAULT false,
  featured_order integer DEFAULT 0,
  featured_from timestamp with time zone,
  featured_until timestamp with time zone,
  view_count integer DEFAULT 0,
  author_id uuid,
  reviewed_by uuid,
  reviewed_at timestamp with time zone,
  is_pinned boolean DEFAULT false,
  metadata jsonb DEFAULT '{}'::jsonb,
  CONSTRAINT conditions_pkey PRIMARY KEY (id),
  CONSTRAINT conditions_author_id_fkey FOREIGN KEY (author_id) REFERENCES public.user_profiles(user_id),
  CONSTRAINT conditions_reviewed_by_fkey FOREIGN KEY (reviewed_by) REFERENCES public.user_profiles(user_id)
);
CREATE TABLE public.facility_profile (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  owner_id uuid NOT NULL,
  facility_type text NOT NULL,
  facility_name text NOT NULL,
  contact_number text NOT NULL,
  whatsapp_number text NOT NULL,
  email text UNIQUE,
  media_urls jsonb,
  featured_image_url text NOT NULL,
  gps_address text NOT NULL,
  street text NOT NULL,
  post_code text NOT NULL,
  area text NOT NULL,
  district text NOT NULL,
  region USER-DEFINED NOT NULL DEFAULT 'greater accra'::region_enum,
  country text NOT NULL DEFAULT 'Ghana'::text,
  latitude double precision NOT NULL,
  longitude double precision NOT NULL,
  location USER-DEFINED,
  ownership text NOT NULL,
  accepts_nhis boolean DEFAULT false,
  services jsonb,
  amenities jsonb,
  first_name text NOT NULL,
  last_name text NOT NULL,
  owner_email text NOT NULL,
  person_contact_number text NOT NULL,
  position text NOT NULL,
  status USER-DEFINED NOT NULL DEFAULT 'pending'::facility_status_enum,
  business_hours jsonb,
  keywords jsonb,
  avg_rating integer DEFAULT 0,
  created_at timestamp without time zone NOT NULL DEFAULT now(),
  approved_at timestamp without time zone,
  updated_at timestamp without time zone,
  is_top_rated boolean DEFAULT false,
  is_featured boolean DEFAULT false,
  submitted_by uuid,
  approved_by uuid,
  rejection_reason text,
  featured_order integer DEFAULT 0,
  view_count integer DEFAULT 0,
  rating_average numeric DEFAULT 0,
  rating_count integer DEFAULT 0,
  subscription_tier text,
  subscription_expires_at timestamp with time zone,
  verification_documents jsonb DEFAULT '[]'::jsonb,
  admin_notes text,
  CONSTRAINT facility_profile_pkey PRIMARY KEY (id),
  CONSTRAINT facility_profile_owner_id_fkey FOREIGN KEY (owner_id) REFERENCES public.user_profiles(user_id),
  CONSTRAINT facility_profile_submitted_by_fkey FOREIGN KEY (submitted_by) REFERENCES public.user_profiles(user_id),
  CONSTRAINT facility_profile_approved_by_fkey FOREIGN KEY (approved_by) REFERENCES public.user_profiles(user_id)
);
CREATE TABLE public.faq_categories (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL UNIQUE,
  created_at timestamp without time zone NOT NULL DEFAULT now(),
  display_order integer DEFAULT 0,
  is_active boolean DEFAULT true,
  CONSTRAINT faq_categories_pkey PRIMARY KEY (id)
);
CREATE TABLE public.faqs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  category_id uuid NOT NULL,
  question text NOT NULL,
  answer text NOT NULL,
  created_at timestamp without time zone NOT NULL DEFAULT now(),
  updated_at timestamp without time zone NOT NULL DEFAULT now(),
  is_featured boolean DEFAULT false,
  view_count integer DEFAULT 0,
  helpful_count integer DEFAULT 0,
  not_helpful_count integer DEFAULT 0,
  author_id uuid,
  status text DEFAULT 'published'::text CHECK (status = ANY (ARRAY['draft'::text, 'published'::text, 'archived'::text])),
  CONSTRAINT faqs_pkey PRIMARY KEY (id),
  CONSTRAINT faqs_category_id_faq_categories_id_fk FOREIGN KEY (category_id) REFERENCES public.faq_categories(id),
  CONSTRAINT faqs_author_id_fkey FOREIGN KEY (author_id) REFERENCES public.user_profiles(user_id)
);
CREATE TABLE public.marketing_profile (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  marketingType USER-DEFINED NOT NULL,
  status USER-DEFINED NOT NULL DEFAULT 'draft'::marketing_status_enum,
  headline text NOT NULL,
  description text NOT NULL,
  imageUrl text NOT NULL,
  cta text NOT NULL,
  links jsonb DEFAULT '[]'::jsonb,
  organization text NOT NULL,
  startDate text NOT NULL,
  endDate text NOT NULL,
  createdAt timestamp without time zone NOT NULL DEFAULT now(),
  updatedAt timestamp without time zone NOT NULL DEFAULT now(),
  CONSTRAINT marketing_profile_pkey PRIMARY KEY (id)
);
CREATE TABLE public.session (
  id text NOT NULL,
  expires_at timestamp without time zone NOT NULL,
  token text NOT NULL UNIQUE,
  created_at timestamp without time zone NOT NULL DEFAULT now(),
  updated_at timestamp without time zone NOT NULL,
  ip_address text,
  user_agent text,
  user_id text NOT NULL,
  CONSTRAINT session_pkey PRIMARY KEY (id),
  CONSTRAINT session_user_id_user_id_fk FOREIGN KEY (user_id) REFERENCES public.user(id)
);
CREATE TABLE public.symptom_causes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  symptom_id uuid,
  cause_name text NOT NULL,
  other_possible_causes jsonb,
  CONSTRAINT symptom_causes_pkey PRIMARY KEY (id),
  CONSTRAINT symptom_causes_symptom_id_symptoms_id_fk FOREIGN KEY (symptom_id) REFERENCES public.symptoms(id)
);
CREATE TABLE public.symptom_body_parts (
  symptom_id uuid NOT NULL,
  body_part_id uuid NOT NULL,
  CONSTRAINT symptom_body_parts_pkey PRIMARY KEY (body_part_id, symptom_id),
  CONSTRAINT symptom_body_parts_symptom_id_symptoms_id_fk FOREIGN KEY (symptom_id) REFERENCES public.symptoms(id),
  CONSTRAINT symptom_body_parts_body_part_id_body_parts_id_fk FOREIGN KEY (body_part_id) REFERENCES public.body_parts(id)
);
CREATE TABLE public.symptom_categories (
  symptom_id uuid NOT NULL,
  category_id uuid NOT NULL,
  CONSTRAINT symptom_categories_pkey PRIMARY KEY (category_id, symptom_id),
  CONSTRAINT symptom_categories_symptom_id_symptoms_id_fk FOREIGN KEY (symptom_id) REFERENCES public.symptoms(id),
  CONSTRAINT symptom_categories_category_id_categories_id_fk FOREIGN KEY (category_id) REFERENCES public.categories(id)
);
CREATE TABLE public.symptom_types (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  symptom_id uuid,
  type_name text NOT NULL,
  about_type jsonb,
  CONSTRAINT symptom_types_pkey PRIMARY KEY (id),
  CONSTRAINT symptom_types_symptom_id_symptoms_id_fk FOREIGN KEY (symptom_id) REFERENCES public.symptoms(id)
);
CREATE TABLE public.symptoms (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text,
  slug text,
  nhs_link text,
  image_url text,
  about jsonb,
  diagnosis jsonb,
  treatment jsonb,
  complications jsonb,
  prevention jsonb,
  contact_your_doctor jsonb,
  more_information jsonb,
  attribution jsonb,
  is_systemic boolean DEFAULT false,
  search_vector tsvector,
  specialist text,
  created_at timestamp without time zone NOT NULL DEFAULT now(),
  updated_at timestamp without time zone NOT NULL DEFAULT now(),
  status text DEFAULT 'published'::text CHECK (status = ANY (ARRAY['draft'::text, 'published'::text, 'archived'::text, 'pending_review'::text])),
  is_featured boolean DEFAULT false,
  view_count integer DEFAULT 0,
  author_id uuid,
  reviewed_by uuid,
  reviewed_at timestamp with time zone,
  metadata jsonb DEFAULT '{}'::jsonb,
  CONSTRAINT symptoms_pkey PRIMARY KEY (id),
  CONSTRAINT symptoms_author_id_fkey FOREIGN KEY (author_id) REFERENCES public.user_profiles(user_id),
  CONSTRAINT symptoms_reviewed_by_fkey FOREIGN KEY (reviewed_by) REFERENCES public.user_profiles(user_id)
);
CREATE TABLE public.user (
  id text NOT NULL,
  name text NOT NULL,
  email text NOT NULL UNIQUE,
  email_verified boolean NOT NULL DEFAULT false,
  image text,
  role text NOT NULL DEFAULT 'user'::text,
  banned boolean,
  created_at timestamp without time zone NOT NULL DEFAULT now(),
  updated_at timestamp without time zone NOT NULL DEFAULT now(),
  CONSTRAINT user_pkey PRIMARY KEY (id)
);
CREATE TABLE public.user_invites (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  email text NOT NULL UNIQUE,
  token text NOT NULL UNIQUE,
  role text NOT NULL,
  created_at timestamp without time zone NOT NULL DEFAULT now(),
  expires_at timestamp without time zone NOT NULL,
  invited_by uuid,
  invite_type text DEFAULT 'user'::text,
  used_at timestamp with time zone,
  used_by uuid,
  is_revoked boolean DEFAULT false,
  revoked_at timestamp with time zone,
  revoked_by uuid,
  CONSTRAINT user_invites_pkey PRIMARY KEY (id),
  CONSTRAINT user_invites_invited_by_fkey FOREIGN KEY (invited_by) REFERENCES public.user_profiles(user_id),
  CONSTRAINT user_invites_used_by_fkey FOREIGN KEY (used_by) REFERENCES public.user_profiles(user_id),
  CONSTRAINT user_invites_revoked_by_fkey FOREIGN KEY (revoked_by) REFERENCES public.user_profiles(user_id)
);
CREATE TABLE public.user_profiles (
  user_id uuid NOT NULL,
  first_name text NOT NULL,
  last_name text NOT NULL,
  created_at timestamp without time zone NOT NULL DEFAULT now(),
  updated_at timestamp without time zone NOT NULL DEFAULT now(),
  sex text,
  dob text,
  user_type text NOT NULL DEFAULT 'customer'::text,
  role text NOT NULL DEFAULT 'user'::text,
  status text NOT NULL DEFAULT 'active'::text CHECK (status = ANY (ARRAY['active'::text, 'inactive'::text, 'suspended'::text, 'banned'::text, 'pending_verification'::text])),
  phone_number text NOT NULL,
  deleted_at timestamp without time zone,
  expo_push_token text,
  last_active timestamp with time zone,
  requires_password_change boolean DEFAULT false,
  has_completed_fitness_onboarding boolean NOT NULL DEFAULT false,
  avatar_url text,
  admin_role USER-DEFINED,
  is_admin boolean DEFAULT false,
  admin_permissions jsonb DEFAULT '[]'::jsonb,
  last_login_at timestamp with time zone,
  login_attempts integer DEFAULT 0,
  locked_until timestamp with time zone,
  mfa_enabled boolean DEFAULT false,
  mfa_verified_at timestamp with time zone,
  whitelisted_ips ARRAY DEFAULT '{}'::text[],
  notes text,
  fitcoins_balance integer DEFAULT 0,
  CONSTRAINT user_profiles_pkey PRIMARY KEY (user_id),
  CONSTRAINT user_profiles_user_id_fk FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.verification (
  id text NOT NULL,
  identifier text NOT NULL,
  value text NOT NULL,
  expires_at timestamp without time zone NOT NULL,
  created_at timestamp without time zone NOT NULL DEFAULT now(),
  updated_at timestamp without time zone NOT NULL DEFAULT now(),
  CONSTRAINT verification_pkey PRIMARY KEY (id)
);
CREATE TABLE public.platform_metrics_history (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  date date DEFAULT CURRENT_DATE UNIQUE,
  total_users integer NOT NULL,
  new_signups_today integer NOT NULL,
  daily_active_users integer NOT NULL,
  monthly_active_users integer NOT NULL,
  sticky_users_count integer NOT NULL,
  male_count integer NOT NULL,
  female_count integer NOT NULL,
  other_gender_count integer NOT NULL,
  total_facilities integer NOT NULL,
  facility_types jsonb NOT NULL,
  active_medication_remainders integer NOT NULL,
  vitals_logged_count integer NOT NULL DEFAULT 0,
  symptoms_reported_count integer NOT NULL DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  upated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT platform_metrics_history_pkey PRIMARY KEY (id)
);
CREATE TABLE public.activity_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  actor_id text,
  actor_name text,
  action_type text NOT NULL,
  target_table text NOT NULL,
  record_id text,
  old_data jsonb,
  new_data jsonb,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT activity_logs_pkey PRIMARY KEY (id)
);
CREATE TABLE public.storage_cleanup_queue (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  file_paths jsonb NOT NULL,
  bucket_name text NOT NULL DEFAULT 'facilities'::text,
  created_at timestamp without time zone DEFAULT now(),
  CONSTRAINT storage_cleanup_queue_pkey PRIMARY KEY (id)
);
CREATE TABLE public.facility_reviews (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  facility_id uuid NOT NULL,
  user_id uuid NOT NULL,
  parent_id uuid,
  is_verified_visit boolean DEFAULT false,
  rating integer CHECK (rating IS NULL OR rating >= 1 AND rating <= 5),
  comment_text text NOT NULL,
  helpful_count integer,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  status USER-DEFINED NOT NULL DEFAULT 'pending'::review_status,
  CONSTRAINT facility_reviews_pkey PRIMARY KEY (id),
  CONSTRAINT facility_reviews_facility_id_fkey FOREIGN KEY (facility_id) REFERENCES public.facility_profile(id),
  CONSTRAINT facility_reviews_parent_id_fkey FOREIGN KEY (parent_id) REFERENCES public.facility_reviews(id),
  CONSTRAINT facility_reviews_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.user_profiles(user_id)
);
CREATE TABLE public.download_stats (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  app_store_count integer,
  play_store_count integer,
  created_at timestamp without time zone,
  CONSTRAINT download_stats_pkey PRIMARY KEY (id)
);
CREATE TABLE public.medication_reminders (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  drug_name text NOT NULL,
  dosage_amount text NOT NULL,
  interval integer NOT NULL,
  start_date timestamp with time zone DEFAULT now(),
  end_date timestamp with time zone,
  is_active boolean DEFAULT true,
  is_enabled boolean DEFAULT true,
  purpose jsonb,
  instructions text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  interval_unit text DEFAULT 'hours'::text,
  drug_type text DEFAULT 'pills'::text,
  drug_color text,
  last_sent_at timestamp with time zone,
  notification_schedule text DEFAULT 'daily'::text,
  schedule_gap integer,
  selected_days ARRAY,
  gap_days integer,
  week_days ARRAY,
  number_of_intakes integer DEFAULT 1,
  CONSTRAINT medication_reminders_pkey PRIMARY KEY (id),
  CONSTRAINT medication_reminders_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.user_profiles(user_id)
);
CREATE TABLE public.twilio_whatsapp_handshakes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  phone_number text NOT NULL,
  facility_email text NOT NULL,
  gps_address text NOT NULL,
  status text,
  expires_at timestamp with time zone DEFAULT (now() + '7 days'::interval),
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT twilio_whatsapp_handshakes_pkey PRIMARY KEY (id)
);
CREATE TABLE public.registrar_locations (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  registrar_id text,
  location USER-DEFINED NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT registrar_locations_pkey PRIMARY KEY (id),
  CONSTRAINT registrar_locations_registrar_id_fkey FOREIGN KEY (registrar_id) REFERENCES public.user(id)
);
CREATE TABLE public.otp_verifications (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  phone_number character varying NOT NULL,
  otp_code character varying NOT NULL,
  expires_at timestamp with time zone NOT NULL,
  verified boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT otp_verifications_pkey PRIMARY KEY (id)
);
CREATE TABLE public.facility_offerings (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  facility_id uuid NOT NULL,
  name text NOT NULL,
  description text,
  price double precision NOT NULL,
  currency text DEFAULT 'GHS'::text,
  offering_type USER-DEFINED NOT NULL,
  duration_months integer,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT facility_offerings_pkey PRIMARY KEY (id),
  CONSTRAINT facility_offerings_facility_id_facility_profile_id_fk FOREIGN KEY (facility_id) REFERENCES public.facility_profile(id)
);
CREATE TABLE public.ibp (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id text NOT NULL UNIQUE,
  business_name text NOT NULL,
  business_category text NOT NULL,
  business_registration_number text,
  specific_category text NOT NULL,
  gps_address text NOT NULL,
  street text NOT NULL,
  city text NOT NULL,
  region text NOT NULL,
  district text NOT NULL,
  area text NOT NULL,
  post_code text,
  country text NOT NULL DEFAULT 'Ghana'::text,
  phone_number text NOT NULL,
  whatsapp_number text,
  website text,
  status USER-DEFINED NOT NULL DEFAULT 'approved'::ibp_status,
  created_at timestamp without time zone NOT NULL DEFAULT now(),
  updated_at timestamp without time zone NOT NULL DEFAULT now(),
  verified_by uuid,
  verified_at timestamp with time zone,
  rejection_reason text,
  is_featured boolean DEFAULT false,
  featured_until timestamp with time zone,
  campaign_budget numeric DEFAULT 0,
  total_spend numeric DEFAULT 0,
  admin_notes text,
  CONSTRAINT ibp_pkey PRIMARY KEY (id),
  CONSTRAINT ibp_user_id_user_id_fk FOREIGN KEY (user_id) REFERENCES public.user(id),
  CONSTRAINT ibp_verified_by_fkey FOREIGN KEY (verified_by) REFERENCES public.user_profiles(user_id)
);
CREATE TABLE public.facility_favorites (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  facility_id uuid NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT facility_favorites_pkey PRIMARY KEY (id),
  CONSTRAINT facility_favorites_facility_id_fkey FOREIGN KEY (facility_id) REFERENCES public.facility_profile(id),
  CONSTRAINT facility_favorites_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.user_profiles(user_id)
);
CREATE TABLE public.tracker_logs (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid,
  period_start_date date NOT NULL,
  period_end_date date,
  cycle_length integer DEFAULT 28,
  period_length integer DEFAULT 5,
  goal text,
  is_consistent text,
  ovulation_date date,
  fertile_window_dates ARRAY,
  next_reminder timestamp with time zone,
  flow_types jsonb,
  symptoms jsonb,
  moods jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT tracker_logs_pkey PRIMARY KEY (id),
  CONSTRAINT tracker_logs_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.user_profiles(user_id)
);
CREATE TABLE public.healthy_living_info (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone DEFAULT now(),
  name text,
  slug text UNIQUE,
  description text,
  content_sections jsonb DEFAULT '[]'::jsonb,
  display_order integer DEFAULT 0,
  parent_id uuid,
  image_url text,
  attribution jsonb DEFAULT '{}'::jsonb,
  status text DEFAULT 'published'::text CHECK (status = ANY (ARRAY['draft'::text, 'published'::text, 'archived'::text, 'pending_review'::text])),
  is_featured boolean DEFAULT false,
  view_count integer DEFAULT 0,
  author_id uuid,
  content_type text DEFAULT 'article'::text,
  tags ARRAY DEFAULT '{}'::text[],
  reading_time_minutes integer,
  CONSTRAINT healthy_living_info_pkey PRIMARY KEY (id),
  CONSTRAINT healthy_living_info_parent_id_fkey FOREIGN KEY (parent_id) REFERENCES public.healthy_living_info(id),
  CONSTRAINT healthy_living_info_author_id_fkey FOREIGN KEY (author_id) REFERENCES public.user_profiles(user_id)
);
CREATE TABLE public.workout_reminders (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  workout_type text NOT NULL,
  duration text NOT NULL,
  time text NOT NULL,
  days ARRAY NOT NULL,
  goals text,
  is_active boolean NOT NULL DEFAULT true,
  is_enabled boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT workout_reminders_pkey PRIMARY KEY (id),
  CONSTRAINT workout_reminders_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.user_profiles(user_id)
);
CREATE TABLE public.user_notes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  note text NOT NULL,
  emotion text CHECK (emotion = ANY (ARRAY['terrible'::text, 'bad'::text, 'okay'::text, 'good'::text, 'great'::text])),
  timestamp timestamp with time zone NOT NULL DEFAULT now(),
  medication_id uuid,
  workout_id uuid,
  note_type text DEFAULT 
CASE
    WHEN (workout_id IS NOT NULL) THEN 'workout'::text
    WHEN (medication_id IS NOT NULL) THEN 'medication'::text
    ELSE 'independent'::text
END,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT user_notes_pkey PRIMARY KEY (id),
  CONSTRAINT user_notes_medication_id_fkey FOREIGN KEY (medication_id) REFERENCES public.medication_reminders(id),
  CONSTRAINT user_notes_workout_id_fkey FOREIGN KEY (workout_id) REFERENCES public.workout_reminders(id),
  CONSTRAINT user_notes_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.user_profiles(user_id)
);
CREATE TABLE public.chat_support (
  id bigint NOT NULL DEFAULT nextval('chat_support_id_seq'::regclass),
  requested_by uuid,
  user_name text,
  subject text,
  message text,
  priority text DEFAULT 'Low'::text CHECK (priority = ANY (ARRAY['Low'::text, 'Medium'::text, 'High'::text])),
  status text DEFAULT 'Open'::text CHECK (status = ANY (ARRAY['Open'::text, 'Closed'::text])),
  is_deleted boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  assigned_to uuid,
  assigned_at timestamp with time zone,
  escalated_at timestamp with time zone,
  escalated_to uuid,
  resolution_notes text,
  resolved_at timestamp with time zone,
  resolved_by uuid,
  category text,
  tags ARRAY DEFAULT '{}'::text[],
  response_time_minutes integer,
  satisfaction_rating integer,
  CONSTRAINT chat_support_pkey PRIMARY KEY (id),
  CONSTRAINT chat_support_requested_by_fkey FOREIGN KEY (requested_by) REFERENCES public.user_profiles(user_id),
  CONSTRAINT chat_support_assigned_to_fkey FOREIGN KEY (assigned_to) REFERENCES public.user_profiles(user_id),
  CONSTRAINT chat_support_escalated_to_fkey FOREIGN KEY (escalated_to) REFERENCES public.user_profiles(user_id),
  CONSTRAINT chat_support_resolved_by_fkey FOREIGN KEY (resolved_by) REFERENCES public.user_profiles(user_id)
);
CREATE TABLE public.notifications (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  title text NOT NULL,
  body text NOT NULL,
  type text NOT NULL,
  metadata jsonb DEFAULT '{}'::jsonb,
  is_read boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  campaign_id uuid,
  is_broadcast boolean DEFAULT false,
  read_at timestamp with time zone,
  CONSTRAINT notifications_pkey PRIMARY KEY (id),
  CONSTRAINT notifications_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.user_profiles(user_id)
);
CREATE TABLE public.conversations (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  type text NOT NULL CHECK (type = ANY (ARRAY['direct'::text, 'group'::text])),
  name text,
  description text,
  avatar_url text,
  created_by uuid,
  is_deleted boolean NOT NULL DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  last_message_at timestamp with time zone,
  last_message_preview text,
  last_message_sender uuid,
  is_group boolean DEFAULT false,
  group_name text,
  group_description text,
  group_category text,
  is_verified_only boolean DEFAULT false,
  max_members integer DEFAULT 500,
  is_flagged boolean DEFAULT false,
  flagged_reason text,
  flagged_at timestamp with time zone,
  flagged_by uuid,
  CONSTRAINT conversations_pkey PRIMARY KEY (id),
  CONSTRAINT conversations_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.user_profiles(user_id),
  CONSTRAINT conversations_last_message_sender_fkey FOREIGN KEY (last_message_sender) REFERENCES public.user_profiles(user_id),
  CONSTRAINT conversations_flagged_by_fkey FOREIGN KEY (flagged_by) REFERENCES public.user_profiles(user_id)
);
CREATE TABLE public.conversation_members (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  conversation_id uuid NOT NULL,
  user_id uuid NOT NULL,
  role text NOT NULL DEFAULT 'member'::text CHECK (role = ANY (ARRAY['member'::text, 'admin'::text, 'owner'::text, 'group_leader'::text])),
  is_muted boolean NOT NULL DEFAULT false,
  is_archived boolean NOT NULL DEFAULT false,
  unread_count integer NOT NULL DEFAULT 0,
  joined_at timestamp with time zone NOT NULL DEFAULT now(),
  left_at timestamp with time zone,
  CONSTRAINT conversation_members_pkey PRIMARY KEY (id),
  CONSTRAINT conversation_members_conversation_id_fkey FOREIGN KEY (conversation_id) REFERENCES public.conversations(id),
  CONSTRAINT conversation_members_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.user_profiles(user_id)
);
CREATE TABLE public.messages (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  conversation_id uuid NOT NULL,
  sender_id uuid NOT NULL,
  content text,
  message_type text NOT NULL DEFAULT 'text'::text CHECK (message_type = ANY (ARRAY['text'::text, 'image'::text, 'voice'::text, 'file'::text, 'system'::text])),
  attachment_url text,
  attachment_name text,
  attachment_size integer,
  reply_to_id uuid,
  is_deleted boolean NOT NULL DEFAULT false,
  edited_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  is_flagged boolean DEFAULT false,
  flag_reason text,
  moderated_by uuid,
  moderated_at timestamp with time zone,
  moderation_action text,
  is_edited boolean DEFAULT false,
  CONSTRAINT messages_pkey PRIMARY KEY (id),
  CONSTRAINT messages_conversation_id_fkey FOREIGN KEY (conversation_id) REFERENCES public.conversations(id),
  CONSTRAINT messages_reply_to_id_fkey FOREIGN KEY (reply_to_id) REFERENCES public.messages(id),
  CONSTRAINT messages_sender_id_fkey FOREIGN KEY (sender_id) REFERENCES public.user_profiles(user_id),
  CONSTRAINT messages_moderated_by_fkey FOREIGN KEY (moderated_by) REFERENCES public.user_profiles(user_id)
);
CREATE TABLE public.message_reads (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  message_id uuid NOT NULL,
  user_id uuid NOT NULL,
  read_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT message_reads_pkey PRIMARY KEY (id),
  CONSTRAINT message_reads_message_id_fkey FOREIGN KEY (message_id) REFERENCES public.messages(id),
  CONSTRAINT message_reads_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.user_profiles(user_id)
);
CREATE TABLE public.facility_conversations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  facility_id uuid NOT NULL,
  conversation_id uuid NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT facility_conversations_pkey PRIMARY KEY (id),
  CONSTRAINT facility_conversations_facility_id_fkey FOREIGN KEY (facility_id) REFERENCES public.facility_profile(id),
  CONSTRAINT facility_conversations_conversation_id_fkey FOREIGN KEY (conversation_id) REFERENCES public.conversations(id)
);
CREATE TABLE public.marketing_discounts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  description text,
  discount_value numeric NOT NULL,
  discount_type text NOT NULL CHECK (discount_type = ANY (ARRAY['percentage'::text, 'fixed'::text, 'bogo'::text])),
  code text NOT NULL UNIQUE,
  max_uses integer,
  current_uses integer DEFAULT 0,
  valid_from timestamp with time zone NOT NULL,
  valid_until timestamp with time zone,
  is_active boolean DEFAULT true,
  applies_to text DEFAULT 'all'::text CHECK (applies_to = ANY (ARRAY['all'::text, 'subscriptions'::text, 'specific'::text])),
  applicable_items jsonb DEFAULT '[]'::jsonb,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  usage_count integer DEFAULT 0,
  usage_limit integer,
  approved_by uuid,
  approved_at timestamp with time zone,
  CONSTRAINT marketing_discounts_pkey PRIMARY KEY (id),
  CONSTRAINT marketing_discounts_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.user_profiles(user_id),
  CONSTRAINT marketing_discounts_approved_by_fkey FOREIGN KEY (approved_by) REFERENCES public.user_profiles(user_id)
);
CREATE TABLE public.marketing_subscriptions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL UNIQUE,
  description text,
  tier_type text NOT NULL,
  price numeric NOT NULL DEFAULT 0.00,
  period text DEFAULT 'free'::text CHECK (period = ANY (ARRAY['free'::text, '3days'::text, '7days'::text, '0.5month'::text, '1month'::text, '3months'::text, '6months'::text, '12months'::text, 'Lifetime'::text])),
  billing_cycle text DEFAULT 'one-time'::text CHECK (billing_cycle = ANY (ARRAY['monthly'::text, 'yearly'::text, 'one-time'::text])),
  privileges ARRAY DEFAULT '{}'::subscription_privilege[],
  tier_limit integer DEFAULT 0,
  is_active boolean DEFAULT true,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  auto_renew boolean DEFAULT true,
  cancelled_at timestamp with time zone,
  cancellation_reason text,
  payment_method text,
  payment_status text DEFAULT 'pending'::text,
  invoice_url text,
  CONSTRAINT marketing_subscriptions_pkey PRIMARY KEY (id),
  CONSTRAINT marketing_subscriptions_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.user_profiles(user_id)
);
CREATE TABLE public.delete_account_requests (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  user_id uuid NOT NULL,
  email text NOT NULL,
  reason text,
  status text DEFAULT 'pending'::text,
  reviewed_by uuid,
  reviewed_at timestamp with time zone,
  rejection_reason text,
  data_export_url text,
  data_export_requested_at timestamp with time zone,
  CONSTRAINT delete_account_requests_pkey PRIMARY KEY (id),
  CONSTRAINT delete_account_requests_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.user_profiles(user_id),
  CONSTRAINT delete_account_requests_reviewed_by_fkey FOREIGN KEY (reviewed_by) REFERENCES public.user_profiles(user_id)
);
CREATE TABLE public.fitness_onboarding_selections (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  user_id uuid NOT NULL UNIQUE,
  fitness_goals ARRAY NOT NULL DEFAULT '{}'::text[],
  fitness_level text NOT NULL,
  workout_weeks integer DEFAULT 2,
  workout_duration integer,
  equipment ARRAY NOT NULL DEFAULT '{}'::text[],
  focus_areas ARRAY NOT NULL DEFAULT '{}'::text[],
  age integer,
  weight_kg numeric,
  height_cm numeric,
  selection_hash text NOT NULL,
  body_type text,
  target_body_shape text,
  workout_locations ARRAY NOT NULL DEFAULT '{}'::text[],
  equipment_access text,
  workout_types ARRAY NOT NULL DEFAULT '{}'::text[],
  unit_system text NOT NULL DEFAULT 'metric'::text,
  workout_days ARRAY NOT NULL DEFAULT '{}'::text[],
  subscription_length integer,
  CONSTRAINT fitness_onboarding_selections_pkey PRIMARY KEY (id),
  CONSTRAINT fitness_onboarding_selections_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.user_profiles(user_id)
);
CREATE TABLE public.fitness_generated_workouts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  selection_hash text NOT NULL UNIQUE,
  workout_plan jsonb NOT NULL,
  generated_by text NOT NULL DEFAULT 'gemini-1.5-flash'::text,
  CONSTRAINT fitness_generated_workouts_pkey PRIMARY KEY (id)
);
CREATE TABLE public.onboarding_requests (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  first_name text NOT NULL,
  last_name text NOT NULL,
  business_name text NOT NULL,
  email text NOT NULL,
  phone_number text,
  request_type text NOT NULL CHECK (request_type = ANY (ARRAY['facility_owner'::text, 'ibp_invite'::text])),
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'approved'::text, 'rejected'::text])),
  notes text,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT onboarding_requests_pkey PRIMARY KEY (id)
);
CREATE TABLE public.admin_activity_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  admin_id uuid NOT NULL,
  admin_email text,
  action_type USER-DEFINED NOT NULL,
  target_table text,
  record_id text,
  old_data jsonb,
  new_data jsonb,
  description text,
  ip_address text,
  user_agent text,
  session_id text,
  severity text DEFAULT 'info'::text CHECK (severity = ANY (ARRAY['info'::text, 'warning'::text, 'critical'::text])),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT admin_activity_logs_pkey PRIMARY KEY (id),
  CONSTRAINT admin_activity_logs_admin_id_fkey FOREIGN KEY (admin_id) REFERENCES public.user_profiles(user_id)
);
CREATE TABLE public.admin_sessions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  admin_id uuid NOT NULL,
  session_token text NOT NULL UNIQUE,
  ip_address text,
  user_agent text,
  device_info text,
  location text,
  started_at timestamp with time zone NOT NULL DEFAULT now(),
  last_active_at timestamp with time zone NOT NULL DEFAULT now(),
  ended_at timestamp with time zone,
  ended_reason text CHECK (ended_reason = ANY (ARRAY['logout'::text, 'timeout'::text, 'forced'::text, 'password_change'::text, 'security_alert'::text])),
  is_active boolean DEFAULT true,
  mfa_verified boolean DEFAULT false,
  CONSTRAINT admin_sessions_pkey PRIMARY KEY (id),
  CONSTRAINT admin_sessions_admin_id_fkey FOREIGN KEY (admin_id) REFERENCES public.user_profiles(user_id)
);
CREATE TABLE public.security_threats (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  threat_level USER-DEFINED NOT NULL,
  threat_type text NOT NULL,
  title text NOT NULL,
  description text,
  affected_users integer DEFAULT 0,
  affected_records text,
  source_ip text,
  source_module text,
  status USER-DEFINED DEFAULT 'open'::threat_status,
  mitigation_action text,
  mitigated_by uuid,
  mitigated_at timestamp with time zone,
  auto_detected boolean DEFAULT false,
  resolved_at timestamp with time zone,
  resolved_by uuid,
  resolution_notes text,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT security_threats_pkey PRIMARY KEY (id),
  CONSTRAINT security_threats_mitigated_by_fkey FOREIGN KEY (mitigated_by) REFERENCES public.user_profiles(user_id),
  CONSTRAINT security_threats_resolved_by_fkey FOREIGN KEY (resolved_by) REFERENCES public.user_profiles(user_id)
);
CREATE TABLE public.platform_broadcasts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  title text NOT NULL,
  message text NOT NULL,
  broadcast_type USER-DEFINED NOT NULL,
  segment_filter jsonb DEFAULT '{}'::jsonb,
  target_regions ARRAY DEFAULT '{}'::text[],
  target_facility_types ARRAY DEFAULT '{}'::text[],
  scheduled_at timestamp with time zone,
  sent_at timestamp with time zone,
  completed_at timestamp with time zone,
  status USER-DEFINED DEFAULT 'draft'::broadcast_status,
  total_recipients integer DEFAULT 0,
  sent_count integer DEFAULT 0,
  failed_count integer DEFAULT 0,
  read_count integer DEFAULT 0,
  created_by uuid NOT NULL,
  approved_by uuid,
  approved_at timestamp with time zone,
  delivery_stats jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT platform_broadcasts_pkey PRIMARY KEY (id),
  CONSTRAINT platform_broadcasts_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.user_profiles(user_id),
  CONSTRAINT platform_broadcasts_approved_by_fkey FOREIGN KEY (approved_by) REFERENCES public.user_profiles(user_id)
);
CREATE TABLE public.content_moderation_flags (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  content_type text NOT NULL CHECK (content_type = ANY (ARRAY['message'::text, 'facility_review'::text, 'forum_post'::text, 'profile'::text, 'comment'::text])),
  content_id text NOT NULL,
  reported_by uuid,
  report_reason text NOT NULL,
  report_detail text,
  ai_detected boolean DEFAULT false,
  ai_confidence numeric,
  ai_reason text,
  status USER-DEFINED DEFAULT 'pending_review'::moderation_status,
  reviewed_by uuid,
  reviewed_at timestamp with time zone,
  action_taken text,
  action_notes text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT content_moderation_flags_pkey PRIMARY KEY (id),
  CONSTRAINT content_moderation_flags_reported_by_fkey FOREIGN KEY (reported_by) REFERENCES public.user_profiles(user_id),
  CONSTRAINT content_moderation_flags_reviewed_by_fkey FOREIGN KEY (reviewed_by) REFERENCES public.user_profiles(user_id)
);
CREATE TABLE public.fitness_challenges (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  title text NOT NULL,
  description text,
  challenge_type text NOT NULL,
  start_date date NOT NULL,
  end_date date NOT NULL,
  goal_metric text,
  goal_value numeric,
  reward_description text,
  reward_image_url text,
  status USER-DEFINED DEFAULT 'draft'::challenge_status,
  is_public boolean DEFAULT true,
  max_participants integer,
  current_participants integer DEFAULT 0,
  completion_count integer DEFAULT 0,
  featured_image_url text,
  tags ARRAY DEFAULT '{}'::text[],
  created_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT fitness_challenges_pkey PRIMARY KEY (id),
  CONSTRAINT fitness_challenges_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.user_profiles(user_id)
);
CREATE TABLE public.fitness_trainers (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL UNIQUE,
  bio text,
  certifications ARRAY DEFAULT '{}'::text[],
  specialties ARRAY DEFAULT '{}'::text[],
  years_experience integer,
  rating_average numeric DEFAULT 0,
  rating_count integer DEFAULT 0,
  is_verified boolean DEFAULT false,
  verified_by uuid,
  verified_at timestamp with time zone,
  status text DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'active'::text, 'suspended'::text, 'rejected'::text])),
  total_sessions integer DEFAULT 0,
  total_clients integer DEFAULT 0,
  profile_video_url text,
  social_links jsonb DEFAULT '{}'::jsonb,
  availability_schedule jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT fitness_trainers_pkey PRIMARY KEY (id),
  CONSTRAINT fitness_trainers_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.user_profiles(user_id),
  CONSTRAINT fitness_trainers_verified_by_fkey FOREIGN KEY (verified_by) REFERENCES public.user_profiles(user_id)
);
CREATE TABLE public.fitness_plans (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  title text NOT NULL,
  description text,
  difficulty_level text NOT NULL,
  duration_weeks integer NOT NULL,
  workouts_per_week integer NOT NULL,
  target_body_parts ARRAY DEFAULT '{}'::text[],
  goals ARRAY DEFAULT '{}'::text[],
  is_premium boolean DEFAULT false,
  is_featured boolean DEFAULT false,
  status text DEFAULT 'published'::text CHECK (status = ANY (ARRAY['draft'::text, 'published'::text, 'archived'::text])),
  author_id uuid,
  author_type text DEFAULT 'trainer'::text CHECK (author_type = ANY (ARRAY['trainer'::text, 'admin'::text, 'ai'::text])),
  total_completions integer DEFAULT 0,
  average_rating numeric DEFAULT 0,
  rating_count integer DEFAULT 0,
  tags ARRAY DEFAULT '{}'::text[],
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT fitness_plans_pkey PRIMARY KEY (id),
  CONSTRAINT workout_plans_author_id_fkey FOREIGN KEY (author_id) REFERENCES public.user_profiles(user_id)
);
CREATE TABLE public.fitness_plan_exercises (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  plan_id uuid NOT NULL,
  exercise_id uuid NOT NULL,
  week_number integer NOT NULL,
  day_number integer NOT NULL,
  order_index integer NOT NULL,
  sets integer,
  reps text,
  duration_seconds integer,
  rest_seconds integer,
  notes text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT fitness_plan_exercises_pkey PRIMARY KEY (id),
  CONSTRAINT workout_plan_exercises_plan_id_fkey FOREIGN KEY (plan_id) REFERENCES public.fitness_plans(id)
);
CREATE TABLE public.escrow_transactions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  transaction_reference text NOT NULL UNIQUE,
  enquiry_id uuid NOT NULL,
  buyer_id uuid NOT NULL,
  seller_id uuid NOT NULL,
  amount numeric NOT NULL,
  currency text DEFAULT 'GHS'::text,
  status USER-DEFINED DEFAULT 'pending'::escrow_status,
  held_at timestamp with time zone,
  released_at timestamp with time zone,
  refunded_at timestamp with time zone,
  released_to text CHECK (released_to = ANY (ARRAY['seller'::text, 'buyer'::text])),
  platform_fee numeric DEFAULT 0,
  payment_provider text,
  payment_provider_reference text,
  dispute_reason text,
  dispute_raised_at timestamp with time zone,
  dispute_resolved_at timestamp with time zone,
  dispute_resolved_by uuid,
  dispute_resolution text,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT escrow_transactions_pkey PRIMARY KEY (id),
  CONSTRAINT escrow_transactions_buyer_id_fkey FOREIGN KEY (buyer_id) REFERENCES public.user_profiles(user_id),
  CONSTRAINT escrow_transactions_seller_id_fkey FOREIGN KEY (seller_id) REFERENCES public.user_profiles(user_id),
  CONSTRAINT escrow_transactions_dispute_resolved_by_fkey FOREIGN KEY (dispute_resolved_by) REFERENCES public.user_profiles(user_id)
);
CREATE TABLE public.medication_enquiries (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  prescription_id uuid,
  medication_name text NOT NULL,
  medication_description text,
  dosage text,
  quantity integer NOT NULL,
  urgency text DEFAULT 'normal'::text CHECK (urgency = ANY (ARRAY['normal'::text, 'urgent'::text, 'emergency'::text])),
  status text DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'confirmed'::text, 'processing'::text, 'shipped'::text, 'delivered'::text, 'cancelled'::text, 'rejected'::text])),
  pharmacy_id uuid,
  pharmacist_notes text,
  delivery_address text,
  delivery_gps text,
  delivery_status USER-DEFINED,
  tracking_number text,
  courier_name text,
  estimated_delivery date,
  actual_delivery timestamp with time zone,
  delivery_proof_url text,
  payment_status text DEFAULT 'pending'::text,
  payment_amount numeric,
  escrow_id uuid,
  is_insured boolean DEFAULT false,
  insurance_provider text,
  insurance_policy_number text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT medication_enquiries_pkey PRIMARY KEY (id),
  CONSTRAINT medication_enquiries_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.user_profiles(user_id),
  CONSTRAINT medication_enquiries_pharmacy_id_fkey FOREIGN KEY (pharmacy_id) REFERENCES public.facility_profile(id),
  CONSTRAINT medication_enquiries_escrow_id_fkey FOREIGN KEY (escrow_id) REFERENCES public.escrow_transactions(id)
);
CREATE TABLE public.pharmacy_campaigns (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  pharmacy_id uuid NOT NULL,
  title text NOT NULL,
  description text,
  campaign_type text NOT NULL,
  target_regions ARRAY DEFAULT '{}'::text[],
  target_medications ARRAY DEFAULT '{}'::text[],
  target_user_segments ARRAY DEFAULT '{}'::text[],
  budget numeric DEFAULT 0,
  spend numeric DEFAULT 0,
  impressions integer DEFAULT 0,
  clicks integer DEFAULT 0,
  conversions integer DEFAULT 0,
  start_date date NOT NULL,
  end_date date,
  status USER-DEFINED DEFAULT 'draft'::campaign_status,
  created_by uuid,
  approved_by uuid,
  approved_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT pharmacy_campaigns_pkey PRIMARY KEY (id),
  CONSTRAINT pharmacy_campaigns_pharmacy_id_fkey FOREIGN KEY (pharmacy_id) REFERENCES public.facility_profile(id),
  CONSTRAINT pharmacy_campaigns_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.user_profiles(user_id),
  CONSTRAINT pharmacy_campaigns_approved_by_fkey FOREIGN KEY (approved_by) REFERENCES public.user_profiles(user_id)
);
CREATE TABLE public.bed_tracker_facilities (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  facility_id uuid NOT NULL UNIQUE,
  total_beds integer NOT NULL DEFAULT 0,
  available_beds integer NOT NULL DEFAULT 0,
  occupied_beds integer NOT NULL DEFAULT 0,
  emergency_beds integer DEFAULT 0,
  icu_beds integer DEFAULT 0,
  icu_available integer DEFAULT 0,
  general_ward_beds integer DEFAULT 0,
  general_ward_available integer DEFAULT 0,
  maternity_beds integer DEFAULT 0,
  maternity_available integer DEFAULT 0,
  pediatric_beds integer DEFAULT 0,
  pediatric_available integer DEFAULT 0,
  last_updated_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_by uuid,
  is_tracking_enabled boolean DEFAULT true,
  alert_threshold integer DEFAULT 5,
  auto_alert_enabled boolean DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT bed_tracker_facilities_pkey PRIMARY KEY (id),
  CONSTRAINT bed_tracker_facilities_facility_id_fkey FOREIGN KEY (facility_id) REFERENCES public.facility_profile(id),
  CONSTRAINT bed_tracker_facilities_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.user_profiles(user_id)
);
CREATE TABLE public.bed_tracker_alerts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  facility_id uuid NOT NULL,
  alert_type text NOT NULL,
  severity text NOT NULL CHECK (severity = ANY (ARRAY['critical'::text, 'warning'::text, 'info'::text])),
  message text NOT NULL,
  bed_type text,
  beds_available integer,
  beds_total integer,
  is_resolved boolean DEFAULT false,
  resolved_at timestamp with time zone,
  resolved_by uuid,
  notification_sent boolean DEFAULT false,
  notification_sent_at timestamp with time zone,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT bed_tracker_alerts_pkey PRIMARY KEY (id),
  CONSTRAINT bed_tracker_alerts_facility_id_fkey FOREIGN KEY (facility_id) REFERENCES public.bed_tracker_facilities(id),
  CONSTRAINT bed_tracker_alerts_resolved_by_fkey FOREIGN KEY (resolved_by) REFERENCES public.user_profiles(user_id)
);
CREATE TABLE public.ambulance_dispatches (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  dispatch_reference text NOT NULL UNIQUE,
  emergency_type text NOT NULL,
  patient_id uuid,
  caller_name text,
  caller_phone text,
  pickup_address text NOT NULL,
  pickup_gps text,
  pickup_region text,
  pickup_area text,
  destination_facility_id uuid,
  destination_address text,
  destination_gps text,
  dispatcher_id uuid,
  driver_id uuid,
  vehicle_id text,
  status text DEFAULT 'pending'::text,
  eta_minutes integer,
  actual_arrival timestamp with time zone,
  actual_completion timestamp with time zone,
  notes text,
  priority text DEFAULT 'normal'::text CHECK (priority = ANY (ARRAY['normal'::text, 'urgent'::text, 'critical'::text])),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT ambulance_dispatches_pkey PRIMARY KEY (id),
  CONSTRAINT ambulance_dispatches_destination_facility_id_fkey FOREIGN KEY (destination_facility_id) REFERENCES public.facility_profile(id),
  CONSTRAINT ambulance_dispatches_dispatcher_id_fkey FOREIGN KEY (dispatcher_id) REFERENCES public.user_profiles(user_id),
  CONSTRAINT ambulance_dispatches_driver_id_fkey FOREIGN KEY (driver_id) REFERENCES public.user_profiles(user_id),
  CONSTRAINT ambulance_dispatches_patient_id_fkey FOREIGN KEY (patient_id) REFERENCES public.user_profiles(user_id)
);
CREATE TABLE public.data_collectors (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL UNIQUE,
  employee_id text NOT NULL UNIQUE,
  region ARRAY DEFAULT '{}'::text[],
  assigned_areas ARRAY DEFAULT '{}'::text[],
  total_submissions integer DEFAULT 0,
  approved_submissions integer DEFAULT 0,
  rejected_submissions integer DEFAULT 0,
  pending_submissions integer DEFAULT 0,
  last_active_at timestamp with time zone,
  is_active boolean DEFAULT true,
  supervisor_id uuid,
  vehicle_assigned text,
  device_info jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT data_collectors_pkey PRIMARY KEY (id),
  CONSTRAINT data_collectors_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.user_profiles(user_id),
  CONSTRAINT data_collectors_supervisor_id_fkey FOREIGN KEY (supervisor_id) REFERENCES public.user_profiles(user_id)
);
CREATE TABLE public.collector_submissions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  collector_id uuid NOT NULL,
  submission_type text NOT NULL CHECK (submission_type = ANY (ARRAY['facility'::text, 'update'::text, 'photo'::text, 'report'::text])),
  facility_id uuid,
  data jsonb NOT NULL DEFAULT '{}'::jsonb,
  photos ARRAY DEFAULT '{}'::text[],
  gps_location text,
  status text DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'approved'::text, 'rejected'::text, 'needs_review'::text])),
  reviewed_by uuid,
  reviewed_at timestamp with time zone,
  review_notes text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT collector_submissions_pkey PRIMARY KEY (id),
  CONSTRAINT collector_submissions_collector_id_fkey FOREIGN KEY (collector_id) REFERENCES public.data_collectors(id),
  CONSTRAINT collector_submissions_facility_id_fkey FOREIGN KEY (facility_id) REFERENCES public.facility_profile(id),
  CONSTRAINT collector_submissions_reviewed_by_fkey FOREIGN KEY (reviewed_by) REFERENCES public.user_profiles(user_id)
);
CREATE TABLE public.notification_templates (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  template_type text NOT NULL CHECK (template_type = ANY (ARRAY['sms'::text, 'push'::text, 'email'::text, 'whatsapp'::text])),
  subject text,
  body text NOT NULL,
  source_module text NOT NULL,
  variables jsonb DEFAULT '[]'::jsonb,
  usage_count integer DEFAULT 0,
  last_used_at timestamp with time zone,
  is_active boolean DEFAULT true,
  created_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT notification_templates_pkey PRIMARY KEY (id),
  CONSTRAINT notification_templates_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.user_profiles(user_id)
);
CREATE TABLE public.notification_automation_rules (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  trigger_event text NOT NULL,
  source_module text NOT NULL,
  channel ARRAY DEFAULT '{}'::text[],
  target_audience text,
  condition_json jsonb DEFAULT '{}'::jsonb,
  template_id uuid,
  is_active boolean DEFAULT true,
  last_fired_at timestamp with time zone,
  fire_count integer DEFAULT 0,
  created_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT notification_automation_rules_pkey PRIMARY KEY (id),
  CONSTRAINT notification_automation_rules_template_id_fkey FOREIGN KEY (template_id) REFERENCES public.notification_templates(id),
  CONSTRAINT notification_automation_rules_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.user_profiles(user_id)
);
CREATE TABLE public.platform_metrics_snapshots (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  snapshot_date date NOT NULL UNIQUE,
  total_users integer DEFAULT 0,
  active_users integer DEFAULT 0,
  new_users integer DEFAULT 0,
  total_facilities integer DEFAULT 0,
  active_facilities integer DEFAULT 0,
  total_ibps integer DEFAULT 0,
  active_ibps integer DEFAULT 0,
  total_workouts integer DEFAULT 0,
  total_challenges integer DEFAULT 0,
  total_messages integer DEFAULT 0,
  total_enquiries integer DEFAULT 0,
  revenue numeric DEFAULT 0,
  subscription_revenue numeric DEFAULT 0,
  ad_revenue numeric DEFAULT 0,
  avg_session_duration_minutes numeric DEFAULT 0,
  retention_rate numeric DEFAULT 0,
  top_regions jsonb DEFAULT '{}'::jsonb,
  top_facility_types jsonb DEFAULT '{}'::jsonb,
  engagement_metrics jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT platform_metrics_snapshots_pkey PRIMARY KEY (id)
);
CREATE TABLE public.facility_scout_referrals (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  referrer_id uuid NOT NULL,
  referred_facility_id uuid,
  referred_user_id uuid,
  referral_type text NOT NULL,
  status text DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'completed'::text, 'rewarded'::text, 'expired'::text])),
  reward_amount numeric DEFAULT 0,
  reward_paid boolean DEFAULT false,
  reward_paid_at timestamp with time zone,
  expiry_date date,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT facility_scout_referrals_pkey PRIMARY KEY (id),
  CONSTRAINT facility_scout_referrals_referrer_id_fkey FOREIGN KEY (referrer_id) REFERENCES public.user_profiles(user_id),
  CONSTRAINT facility_scout_referrals_referred_facility_id_fkey FOREIGN KEY (referred_facility_id) REFERENCES public.facility_profile(id),
  CONSTRAINT facility_scout_referrals_referred_user_id_fkey FOREIGN KEY (referred_user_id) REFERENCES public.user_profiles(user_id)
);
CREATE TABLE public.hcp_verifications (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL UNIQUE,
  license_number text NOT NULL,
  license_type text NOT NULL,
  issuing_body text NOT NULL,
  license_expiry date NOT NULL,
  specialty text,
  years_of_practice integer,
  documents jsonb DEFAULT '[]'::jsonb,
  verification_status text DEFAULT 'pending'::text CHECK (verification_status = ANY (ARRAY['pending'::text, 'under_review'::text, 'verified'::text, 'rejected'::text, 'expired'::text])),
  verified_by uuid,
  verified_at timestamp with time zone,
  rejection_reason text,
  next_verification_due date,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT hcp_verifications_pkey PRIMARY KEY (id),
  CONSTRAINT hcp_verifications_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.user_profiles(user_id),
  CONSTRAINT hcp_verifications_verified_by_fkey FOREIGN KEY (verified_by) REFERENCES public.user_profiles(user_id)
);
CREATE TABLE public.subscription_plans (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  slug text NOT NULL UNIQUE,
  description text,
  tier text NOT NULL CHECK (tier = ANY (ARRAY['free'::text, 'standard'::text, 'premium'::text, 'featured'::text])),
  price_monthly numeric DEFAULT 0,
  price_yearly numeric DEFAULT 0,
  currency text DEFAULT 'GHS'::text,
  features jsonb DEFAULT '[]'::jsonb,
  max_listings integer,
  max_ad_campaigns integer,
  max_storage_gb integer,
  is_active boolean DEFAULT true,
  display_order integer DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT subscription_plans_pkey PRIMARY KEY (id)
);
CREATE TABLE public.user_subscriptions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  plan_id uuid NOT NULL,
  status text DEFAULT 'active'::text CHECK (status = ANY (ARRAY['active'::text, 'cancelled'::text, 'expired'::text, 'suspended'::text, 'pending'::text])),
  started_at timestamp with time zone NOT NULL DEFAULT now(),
  expires_at timestamp with time zone,
  cancelled_at timestamp with time zone,
  cancellation_reason text,
  auto_renew boolean DEFAULT true,
  payment_method text,
  last_payment_at timestamp with time zone,
  next_payment_due timestamp with time zone,
  total_payments integer DEFAULT 0,
  total_paid numeric DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT user_subscriptions_pkey PRIMARY KEY (id),
  CONSTRAINT user_subscriptions_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.user_profiles(user_id),
  CONSTRAINT user_subscriptions_plan_id_fkey FOREIGN KEY (plan_id) REFERENCES public.subscription_plans(id)
);
CREATE TABLE public.transaction_records (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  transaction_reference text NOT NULL UNIQUE,
  user_id uuid,
  facility_id uuid,
  transaction_type text NOT NULL CHECK (transaction_type = ANY (ARRAY['payment'::text, 'refund'::text, 'subscription'::text, 'ad_spend'::text, 'withdrawal'::text, 'deposit'::text, 'platform_fee'::text, 'commission'::text])),
  amount numeric NOT NULL,
  currency text DEFAULT 'GHS'::text,
  status text DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'completed'::text, 'failed'::text, 'cancelled'::text, 'disputed'::text])),
  payment_provider text,
  provider_reference text,
  metadata jsonb DEFAULT '{}'::jsonb,
  description text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT transaction_records_pkey PRIMARY KEY (id),
  CONSTRAINT transaction_records_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.user_profiles(user_id),
  CONSTRAINT transaction_records_facility_id_fkey FOREIGN KEY (facility_id) REFERENCES public.facility_profile(id)
);
CREATE TABLE public.job_postings (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  facility_id uuid NOT NULL,
  title text NOT NULL,
  description text,
  requirements ARRAY DEFAULT '{}'::text[],
  job_type text NOT NULL CHECK (job_type = ANY (ARRAY['full_time'::text, 'part_time'::text, 'contract'::text, 'temporary'::text, 'internship'::text])),
  specialty text,
  experience_level text,
  salary_min numeric,
  salary_max numeric,
  salary_currency text DEFAULT 'GHS'::text,
  location text,
  region text,
  application_url text,
  contact_email text,
  status text DEFAULT 'draft'::text CHECK (status = ANY (ARRAY['draft'::text, 'published'::text, 'closed'::text, 'filled'::text, 'expired'::text])),
  published_at timestamp with time zone,
  expires_at timestamp with time zone,
  view_count integer DEFAULT 0,
  application_count integer DEFAULT 0,
  created_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT job_postings_pkey PRIMARY KEY (id),
  CONSTRAINT job_postings_facility_id_fkey FOREIGN KEY (facility_id) REFERENCES public.facility_profile(id),
  CONSTRAINT job_postings_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.user_profiles(user_id)
);
CREATE TABLE public.job_applications (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  job_id uuid NOT NULL,
  applicant_id uuid NOT NULL,
  cover_letter text,
  resume_url text,
  portfolio_url text,
  status text DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'reviewed'::text, 'shortlisted'::text, 'rejected'::text, 'hired'::text])),
  reviewed_by uuid,
  reviewed_at timestamp with time zone,
  review_notes text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT job_applications_pkey PRIMARY KEY (id),
  CONSTRAINT job_applications_job_id_fkey FOREIGN KEY (job_id) REFERENCES public.job_postings(id),
  CONSTRAINT job_applications_applicant_id_fkey FOREIGN KEY (applicant_id) REFERENCES public.user_profiles(user_id),
  CONSTRAINT job_applications_reviewed_by_fkey FOREIGN KEY (reviewed_by) REFERENCES public.user_profiles(user_id)
);
CREATE TABLE public.fitness_content_schedule (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  content_type text NOT NULL CHECK (content_type = ANY (ARRAY['workout'::text, 'challenge'::text, 'broadcast'::text, 'article'::text])),
  reference_id uuid,
  target_audience USER-DEFINED DEFAULT 'all_users'::broadcast_type,
  scheduled_at timestamp with time zone NOT NULL,
  status USER-DEFINED DEFAULT 'scheduled'::broadcast_status,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT fitness_content_schedule_pkey PRIMARY KEY (id),
  CONSTRAINT fitness_content_schedule_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.user_profiles(user_id)
);
CREATE TABLE public.fitness_ai_campaigns (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  title text NOT NULL,
  model_type text NOT NULL,
  campaign_status USER-DEFINED DEFAULT 'draft'::campaign_status,
  context_data jsonb NOT NULL,
  result_data jsonb,
  created_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT fitness_ai_campaigns_pkey PRIMARY KEY (id),
  CONSTRAINT fitness_ai_campaigns_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.user_profiles(user_id)
);
CREATE TABLE public.fitness_ai_calls (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  campaign_id uuid,
  user_id uuid,
  model_name text NOT NULL,
  prompt_snippet text,
  response_time_ms integer,
  token_usage integer,
  estimated_cost numeric,
  status text CHECK (status = ANY (ARRAY['success'::text, 'error'::text, 'timeout'::text])),
  error_message text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT fitness_ai_calls_pkey PRIMARY KEY (id),
  CONSTRAINT fitness_ai_calls_campaign_id_fkey FOREIGN KEY (campaign_id) REFERENCES public.fitness_ai_campaigns(id),
  CONSTRAINT fitness_ai_calls_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.user_profiles(user_id)
);
CREATE TABLE public.fitness_outdoor_routes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  description text,
  category text NOT NULL,
  difficulty USER-DEFINED DEFAULT 'low'::threat_level,
  surface_type text,
  gps_data jsonb,
  start_location_name text,
  distance_km numeric,
  estimated_duration_mins integer,
  verification_status USER-DEFINED DEFAULT 'pending_review'::moderation_status,
  verified_by uuid,
  image_urls ARRAY DEFAULT '{}'::text[],
  is_active boolean DEFAULT true,
  created_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT fitness_outdoor_routes_pkey PRIMARY KEY (id),
  CONSTRAINT fitness_outdoor_routes_verified_by_fkey FOREIGN KEY (verified_by) REFERENCES public.user_profiles(user_id),
  CONSTRAINT fitness_outdoor_routes_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.user_profiles(user_id)
);
CREATE TABLE public.fitness_outdoor_events (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  route_id uuid,
  title text NOT NULL,
  description text,
  start_at timestamp with time zone NOT NULL,
  max_participants integer,
  current_participants integer DEFAULT 0,
  status USER-DEFINED DEFAULT 'upcoming'::challenge_status,
  created_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  latitude double precision,
  longitude double precision,
  area text,
  category text,
  CONSTRAINT fitness_outdoor_events_pkey PRIMARY KEY (id),
  CONSTRAINT fitness_outdoor_events_route_id_fkey FOREIGN KEY (route_id) REFERENCES public.fitness_outdoor_routes(id),
  CONSTRAINT fitness_outdoor_events_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.user_profiles(user_id)
);
CREATE TABLE public.fitness_outdoor_reviews (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  route_id uuid,
  user_id uuid,
  rating integer CHECK (rating >= 1 AND rating <= 5),
  comment text,
  is_flagged boolean DEFAULT false,
  moderation_status USER-DEFINED DEFAULT 'approved'::moderation_status,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT fitness_outdoor_reviews_pkey PRIMARY KEY (id),
  CONSTRAINT fitness_outdoor_reviews_route_id_fkey FOREIGN KEY (route_id) REFERENCES public.fitness_outdoor_routes(id),
  CONSTRAINT fitness_outdoor_reviews_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.user_profiles(user_id)
);
CREATE TABLE public.fitness_health_platforms (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  platform_name text NOT NULL UNIQUE,
  is_enabled boolean DEFAULT true,
  config_data jsonb DEFAULT '{}'::jsonb,
  sync_frequency_mins integer DEFAULT 60,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT fitness_health_platforms_pkey PRIMARY KEY (id)
);
CREATE TABLE public.fitness_health_sync_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  platform_id uuid,
  status text CHECK (status = ANY (ARRAY['success'::text, 'failure'::text])),
  error_details text,
  retry_count integer DEFAULT 0,
  synced_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT fitness_health_sync_logs_pkey PRIMARY KEY (id),
  CONSTRAINT fitness_health_sync_logs_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.user_profiles(user_id),
  CONSTRAINT fitness_health_sync_logs_platform_id_fkey FOREIGN KEY (platform_id) REFERENCES public.fitness_health_platforms(id)
);
CREATE TABLE public.fitness_whatsapp_groups (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  description text,
  group_type text,
  whatsapp_link text,
  member_count integer DEFAULT 0,
  is_active boolean DEFAULT true,
  last_message_at timestamp with time zone,
  status USER-DEFINED DEFAULT 'approved'::moderation_status,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT fitness_whatsapp_groups_pkey PRIMARY KEY (id)
);
CREATE TABLE public.fitness_whatsapp_broadcasts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  group_id uuid,
  message text NOT NULL,
  broadcast_type USER-DEFINED DEFAULT 'all_users'::broadcast_type,
  sent_at timestamp with time zone DEFAULT now(),
  sent_to_count integer DEFAULT 0,
  open_rate numeric,
  status USER-DEFINED DEFAULT 'sent'::broadcast_status,
  created_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT fitness_whatsapp_broadcasts_pkey PRIMARY KEY (id),
  CONSTRAINT fitness_whatsapp_broadcasts_group_id_fkey FOREIGN KEY (group_id) REFERENCES public.fitness_whatsapp_groups(id),
  CONSTRAINT fitness_whatsapp_broadcasts_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.user_profiles(user_id)
);
CREATE TABLE public.fitness_exercises (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  exercise_name text NOT NULL,
  category text NOT NULL,
  primary_muscle_group text NOT NULL,
  secondary_muscles text,
  equipment_required text NOT NULL,
  difficulty_level text,
  default_sets text,
  default_reps_duration text,
  rest_time_seconds text,
  description text,
  benefits text,
  muscles_worked_raw text,
  video_url text,
  thumbnail_url text,
  tier text NOT NULL DEFAULT 'pro'::text,
  is_featured boolean NOT NULL DEFAULT false,
  is_active boolean NOT NULL DEFAULT true,
  status text NOT NULL DEFAULT 'published'::text CHECK (status = ANY (ARRAY['draft'::text, 'published'::text, 'archived'::text])),
  tags ARRAY NOT NULL DEFAULT '{}'::text[],
  view_count integer NOT NULL DEFAULT 0,
  completion_count integer NOT NULL DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  met_value real,
  CONSTRAINT fitness_exercises_pkey PRIMARY KEY (id)
);
CREATE TABLE public.fitness_users (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  fitness_plan_id uuid,
  current_level text,
  preferences jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT fitness_users_pkey PRIMARY KEY (id),
  CONSTRAINT fitness_users_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.user_profiles(user_id),
  CONSTRAINT fitness_users_fitness_plan_id_fkey FOREIGN KEY (fitness_plan_id) REFERENCES public.fitness_plans(id)
);
CREATE TABLE public.exercise_views (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  exercise_id uuid NOT NULL,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
  CONSTRAINT exercise_views_pkey PRIMARY KEY (id),
  CONSTRAINT exercise_views_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.user_profiles(user_id),
  CONSTRAINT exercise_views_exercise_id_fkey FOREIGN KEY (exercise_id) REFERENCES public.fitness_exercises(id)
);
CREATE TABLE public.fitness_challenge_participants (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  challenge_id uuid NOT NULL,
  user_id uuid NOT NULL,
  joined_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
  progress_pct numeric DEFAULT 0.00,
  status text DEFAULT 'active'::text CHECK (status = ANY (ARRAY['active'::text, 'abandoned'::text, 'completed'::text])),
  CONSTRAINT fitness_challenge_participants_pkey PRIMARY KEY (id),
  CONSTRAINT fitness_challenge_participants_challenge_id_fkey FOREIGN KEY (challenge_id) REFERENCES public.fitness_challenges(id),
  CONSTRAINT fitness_challenge_participants_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.user_profiles(user_id)
);
CREATE TABLE public.exercise_sessions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  plan_id uuid,
  status text NOT NULL DEFAULT 'in_progress'::text CHECK (status = ANY (ARRAY['in_progress'::text, 'completed'::text, 'abandoned'::text])),
  start_time timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  end_time timestamp with time zone,
  total_duration_minutes integer,
  kcal_burned numeric,
  notes text,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT exercise_sessions_pkey PRIMARY KEY (id),
  CONSTRAINT exercise_sessions_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.user_profiles(user_id),
  CONSTRAINT exercise_sessions_plan_id_fkey FOREIGN KEY (plan_id) REFERENCES public.fitness_generated_workouts(id)
);
CREATE TABLE public.exercise_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  session_id uuid NOT NULL,
  exercise_id uuid NOT NULL,
  set_number integer NOT NULL,
  target_reps text,
  reps_completed integer NOT NULL,
  weight_kg numeric,
  rest_time_taken_seconds integer,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT exercise_logs_pkey PRIMARY KEY (id),
  CONSTRAINT exercise_logs_session_id_fkey FOREIGN KEY (session_id) REFERENCES public.exercise_sessions(id),
  CONSTRAINT exercise_logs_exercise_id_fkey FOREIGN KEY (exercise_id) REFERENCES public.fitness_exercises(id)
);
CREATE TABLE public.notification_campaigns (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  template_id uuid,
  title text NOT NULL,
  body text NOT NULL,
  type text NOT NULL,
  metadata jsonb DEFAULT '{}'::jsonb,
  segment_filter jsonb,
  scheduled_at timestamp with time zone,
  sent_at timestamp with time zone,
  failed_at timestamp with time zone,
  failure_reason text,
  delivery_stats jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT notification_campaigns_pkey PRIMARY KEY (id)
);
CREATE TABLE public.medication_adherence (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  reminder_id uuid NOT NULL,
  user_id uuid NOT NULL,
  status USER-DEFINED NOT NULL DEFAULT 'missed'::adherence_status,
  scheduled_time timestamp with time zone NOT NULL,
  action_time timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT medication_adherence_pkey PRIMARY KEY (id),
  CONSTRAINT medication_adherence_reminder_id_fkey FOREIGN KEY (reminder_id) REFERENCES public.medication_reminders(id),
  CONSTRAINT medication_adherence_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.user_profiles(user_id)
);