-- Epic 3.4: private bucket for GDPR data-export packages generated by
-- features/delete-account-requests/api/export-request.ts. Same posture as
-- the other private buckets added in 20260908_epic2_5_storage_hardening.sql
-- (prescriptions, job-documents, chat-attachments, hcp-verification):
-- service-role-mediated only, no anon/authenticated grants, no client
-- storage policies. Zips are JSON exports of a single user's rows, not
-- photos, so a 50MB cap is generous headroom.
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values
  ('user-data-exports', 'user-data-exports', false, 52428800, array['application/zip'])
on conflict (id) do nothing;
