revoke all on function public.get_my_trainer_workspace(uuid) from authenticated, service_role;
revoke all on function public.upsert_my_trainer_workspace(uuid, jsonb) from authenticated, service_role;
revoke all on function public.get_my_trainer_sessions(uuid, date, date) from authenticated, service_role;
revoke all on function public.get_my_trainer_clients(uuid) from authenticated, service_role;
revoke all on function public.get_my_trainer_session_attendees(uuid) from authenticated, service_role;
revoke all on function public.check_in_group_attendee(uuid, uuid) from authenticated, service_role;
revoke all on function public.get_my_trainer_programmes(uuid) from authenticated, service_role;
revoke all on function public.upsert_my_trainer_programme(uuid, uuid, jsonb) from authenticated, service_role;
drop function if exists public.get_my_trainer_workspace(uuid);
drop function if exists public.upsert_my_trainer_workspace(uuid, jsonb);
drop function if exists public.get_my_trainer_sessions(uuid, date, date);
drop function if exists public.get_my_trainer_clients(uuid);
drop function if exists public.get_my_trainer_session_attendees(uuid);
drop function if exists public.check_in_group_attendee(uuid, uuid);
drop function if exists public.get_my_trainer_programmes(uuid);
drop function if exists public.upsert_my_trainer_programme(uuid, uuid, jsonb);
alter table public.provider_booking_group_attendees drop column if exists pass_issued_at;
alter table public.provider_booking_group_attendees drop column if exists qr_token;
notify pgrst, 'reload schema';
