export const navIcons = {
  Dashboard: "📊",
  Transactions: "💳",
  Admins: "🔐",
  Users: "👥",
  "Task Manager": "📋",
  Facilities: "🏢",
  "Diseases & Conditions": "🦠",
  "Human Anatomy": "🧍",
  Symptoms: "🌡️",
  "Healthy Living": "🌿",
  Fitness: "💪",
  "Period Tracker": "💧",
  "Medication Reminder": "💊",
  "Healthcare Professionals": "👨‍⚕️",
  Jobs: "💼",
  "Medication Enquiry": "🔍",
  "BedTracker (PKM)": "🛏️",
  "Reviews & Ratings": "⭐",
  Map: "🗺️",
  Marketing: "📢",
  Chats: "💬",
  FacilityScout: "🕵️",
  FAQ: "❓",
  Notifications: "🔔",
  "AI Hub": "🤖",
  "Security Center": "🛡️",
  "Platform Schematic": "🏗️",
  Settings: "⚙️",
  "Delete Account Requests": "🗑️",
  Logout: "🚪",
};
